/* Device-local startup preference and safe, user-initiated PWA installation/update. */
(function(){'use strict';
const VERSION='1.4.0',KEY='nk:device-start-profile:2';
const $=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let promptEvent=null,updating=false,reloadRequested=false,touchedForms=new WeakSet();
function read(){try{const p=JSON.parse(localStorage.getItem(KEY)||'null');if(p&&['ask','last','fixed'].includes(p.mode)&&(!p.id||typeof p.id==='string'))return p;}catch{}return {mode:'last'};}
function save(p,profiles){if(!['ask','last','fixed'].includes(p.mode)||p.mode==='fixed'&&!profiles.some(x=>x.id===p.id))throw Error('Bitte ein gültiges Startprofil wählen.');localStorage.setItem(KEY,JSON.stringify({mode:p.mode,...(p.mode==='fixed'?{id:p.id}:{})}));}
function preferred(profiles,last){const p=read();if(p.mode==='ask')return null;if(p.mode==='fixed')return profiles.some(x=>x.id===p.id)?p.id:null;return profiles.some(x=>x.id===last)?last:profiles.length===1?profiles[0].id:null;}
function controls(profiles){const p=read(),v=p.mode==='fixed'?'profile:'+p.id:p.mode;return `<section class="device-preference"><h3>Standardprofil auf diesem Gerät</h3><label for="device-profile-choice">Beim nächsten Start nach der Anmeldung öffnen</label><select id="device-profile-choice"><option value="ask" ${v==='ask'?'selected':''}>Jedes Mal fragen</option><option value="last" ${v==='last'?'selected':''}>Zuletzt genutztes Profil</option>${profiles.map(x=>`<option value="profile:${E(x.id)}" ${v==='profile:'+x.id?'selected':''}>Immer ${E(x.name)}</option>`).join('')}</select><button type="button" class="button secondary" data-nk="device-save">Startprofil speichern</button><p class="tiny">Gilt nur für diesen Browser bzw. diese installierte Web-App, nicht für andere Geräte. Ein manueller Profilwechsel ändert das feste Startprofil nicht. Keine automatische Anmeldung; noch nicht gesendete Einträge haben beim Wiederherstellen Vorrang.</p></section>`;}
function status(s){const el=$('#device-update-status');if(el)el.textContent=s;}
function standalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;}
function installationHelp(){let d=$('#device-install-dialog');if(!d){d=document.createElement('dialog');d.id='device-install-dialog';document.body.append(d);}const ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);d.innerHTML=`<div class="modal-head"><h2>App-Symbol auf dem Handy</h2><button class="icon-btn" aria-label="Schliessen" data-device-close>×</button></div>${standalone()?'<p>Die App ist bereits in einem eigenen App-Fenster geöffnet.</p>':ios?'<p>Öffne diesen Link in <b>Safari</b>. Tippe auf <b>Teilen → Zum Home-Bildschirm</b>, aktiviere gegebenenfalls <b>Als Web-App öffnen</b> und bestätige <b>Hinzufügen</b>.</p><p>iPhone und iPad verlangen diese Bestätigung; die Webseite kann kein Symbol unbemerkt erstellen.</p>':'<p>Öffne den Link in <b>Chrome</b>. Wähle im Browsermenü <b>App installieren</b> oder <b>Zum Startbildschirm hinzufügen</b>. Sobald dein Browser die Installation anbietet, kann dieser Button auch direkt den Installationsdialog öffnen.</p>'}<p class="small">Danach über das Kompass-Symbol starten. Das Standardprofil kannst du nach der Anmeldung im Profilmenü für dieses Gerät festlegen.</p><p class="tiny">Keine erneute Registrierung nötig. Ein anderer Browser oder eine getrennte Web-App-Installation kann einen eigenen Speicher haben.</p>`;d.querySelector('[data-device-close]').onclick=()=>d.close();if(!d.open)d.showModal();}
async function install(){if(standalone()||!promptEvent){installationHelp();return;}const event=promptEvent;promptEvent=null;try{await event.prompt();const r=await event.userChoice;status(r?.outcome==='accepted'?'Installation bestätigt.':'Installation nicht durchgeführt.');}catch{installationHelp();}}
function unsavedForm(){if(document.querySelector('#scan-dialog[open],#product-finder-dialog[open]'))return true;return [...document.querySelectorAll('#app:not([hidden]) #profile-form,#dialog[open] #food-form,#dialog[open] #custom-food-form,#dialog[open] #recipe-log-form,#dialog[open] #entry-edit-form,#dialog[open] #retail-review-form')].some(f=>touchedForms.has(f));}
async function safeToReload(){if(window.NK_APP?.hasDraft||unsavedForm()){status('Bitte offene Eingaben zuerst speichern oder den Dialog schliessen. Kein Update durchgeführt.');return false;}try{if(window.NK_HOUSEHOLD?.authenticated)await window.NK_HOUSEHOLD.flush();if(window.NK_HOUSEHOLD?.pending)throw Error('Änderungen noch nicht synchronisiert.');return true;}catch(e){status('Update pausiert: '+e.message);return false;}}
async function update(){if(updating)return;updating=true;try{if(!navigator.onLine)throw Error('Offline. Zum Prüfen bitte Internetverbindung herstellen.');if(!('serviceWorker' in navigator))throw Error('Dieser Browser unterstützt hier keine App-Updates.');status('Prüfe auf App-Updates …');const scope=new URL('./',location.href).href;let reg=await navigator.serviceWorker.getRegistration(scope);if(!reg)reg=await navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'});if(reg.scope!==scope)throw Error('Die Registrierung gehört zu einer anderen App.');await reg.update();if(reg.installing){const worker=reg.installing;await Promise.race([new Promise(resolve=>{const done=()=>{if(['installed','redundant'].includes(worker.state))resolve();};worker.addEventListener('statechange',done);done();}),new Promise(resolve=>setTimeout(resolve,10000))]);}
 if(reg.waiting){if(!await safeToReload())return;reloadRequested=true;reg.waiting.postMessage('ACTIVATE_UPDATE');status('Update wird angewendet …');setTimeout(()=>{if(reloadRequested){reloadRequested=false;status('Update bereit. Bitte die App einmal schliessen und erneut öffnen.');}},12000);return;}
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),10000);let remote;try{const r=await fetch('./version.json?t='+Date.now(),{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error('Versionsprüfung fehlgeschlagen.');remote=await r.json();}finally{clearTimeout(timeout);}if(remote.version!==VERSION){if(await safeToReload())location.reload();}else status('Aktuell · Version '+VERSION+'. Deine Einträge bleiben erhalten.');
 }catch(e){status('Keine Änderung: '+e.message);}finally{updating=false;}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e;});
window.addEventListener('appinstalled',()=>{promptEvent=null;status('App installiert.');const b=$('[data-device="install"]');if(b)b.textContent='App installiert';});
if('serviceWorker' in navigator)navigator.serviceWorker.addEventListener('controllerchange',async()=>{if(reloadRequested){reloadRequested=false;if(await safeToReload())location.reload();}else status('App-Version aktualisiert. Offene Eingaben bleiben erhalten; bei Bedarf neu öffnen.');});
document.addEventListener('click',e=>{const b=e.target.closest('[data-device]');if(!b)return;if(b.dataset.device==='install'){e.preventDefault();install();}if(b.dataset.device==='update'){e.preventDefault();update();}});
document.addEventListener('input',e=>{const f=e.target.closest('#profile-form,#food-form,#custom-food-form,#recipe-log-form,#entry-edit-form,#retail-review-form');if(f)touchedForms.add(f);});
document.addEventListener('nk-profile-loaded',()=>{touchedForms=new WeakSet();const b=$('#device-profile-button');if(b)b.hidden=false;});
window.NK_DEVICE={version:VERSION,read,save,preferred,controls,install,update,hasUnsavedForm:unsavedForm};
})();
