/* Product names, barcode and Coop links share one reviewed import flow. */
(function(root){'use strict';
const endpoint='https://wpmyuzpcraduhaybjvmb.supabase.co/functions/v1/nutrient-product-finder',C=root.NK,PC=root.NK_PRODUCT_CORE;
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const clean=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss');
let generation=0,profile='',matches=[],lastQuery='',limit=20;
const seed=root.NK_PRODUCT_SOURCES||[];
function known(){return [...(root.NK_APP?.getState().foods||[]),...(root.NK_SHARED?.foods()||[]),...root.NK_DATA.foods];}
function all(){const map=new Map();for(const f of [...known(),...seed,...(root.NK_RETAIL_FOODS||[])])if(!map.has(f.id))map.set(f.id,f);return [...map.values()];}
function canonical(s){try{return PC.coopURL(s);}catch{try{const u=new URL(s);u.search='';u.hash='';return u.href.replace(/\/$/,'');}catch{return '';}}}
function duplicates(f){return known().filter(x=>x.id===f.id||x.shared?.sourceId===f.id||f.sourceUrl&&canonical(x.sourceUrl)===canonical(f.sourceUrl));}
function local(q){const words=clean(q).split(/\s+/).filter(Boolean);return all().filter(f=>words.every(w=>clean(f.name+' '+f.synonyms+' '+(f.catalog?.code||'')+' '+f.id).includes(w)));}
function notice(t){const el=document.getElementById('finder-status');if(el)el.textContent=t;}
function render(){const el=document.getElementById('finder-results');if(!el)return;el.innerHTML=matches.slice(0,limit).map((f,i)=>{const n=f.n,external=f.needsBasisConfirmation,source=f.shared?'Unser Haushalt · '+f.shared.ownerName:f.sourceSnapshot?'Geprüfter Coop-Quellenstand · '+f.importedAt:f.catalog?.type==='off'?'Open Food Facts · Community-Daten':f.source||'Hinterlegter Katalog';return `<div class="finder-item"><button type="button" class="muted-link" data-found="${i}"><b>${E(f.name)}</b><small>${E(source)}</small><small>${n.energy==null?'Energie unbekannt':E(new Intl.NumberFormat('de-CH',{maximumFractionDigits:1}).format(n.energy))+' kcal'} · ${n.protein==null?'Protein unbekannt':E(new Intl.NumberFormat('de-CH',{maximumFractionDigits:1}).format(n.protein))+' g Protein'} · ${external?'100-g-/100-ml-Spalte prüfen':'pro 100 '+E(f.basis)}</small></button></div>`;}).join('')+(matches.length>limit?'<button type="button" class="button secondary wide" data-finder-more>Weitere Treffer</button>':'');}
function mount(){if(!root.NK_APP||document.getElementById('app').hidden)return;if(profile!==root.NK_HOUSEHOLD?.id){profile=root.NK_HOUSEHOLD?.id;generation++;matches=[];lastQuery='';}
 const search=document.getElementById('food-search');if(!search||document.getElementById('finder-form'))return;
 const box=document.createElement('section');box.className='finder-box';box.innerHTML=`<h2>Produkt automatisch finden</h2><p class="small">Name, Barcode oder Coop-Produktlink. Erst vorhandene Produkte suchen, dann bei Bedarf online ergänzen.</p><form id="finder-form"><label class="screen-reader" for="finder-query">Produktname, Barcode oder Coop-Link</label><div class="finder-entry"><input id="finder-query" type="text" maxlength="2000" placeholder="Redefine Flank Steak oder https://www.coop.ch/…" autocomplete="off" value="${E(lastQuery)}"><button class="button" type="submit">Nährwerte finden</button></div></form><p id="finder-status" class="small" role="status"></p><div class="finder-list" id="finder-results"></div><div class="finder-actions"><button type="button" class="button secondary" id="finder-online">Online nach Namen suchen</button><button type="button" class="button secondary" data-nk-scan>Packung fotografieren</button></div><p class="tiny">Nur die Suchwörter bzw. die bereinigte Produktadresse werden an den Suchdienst übermittelt, keine Profile oder Tagebucheinträge. Externe Daten und Portionsspalte vor dem Speichern prüfen. Händler können automatischen Zugriff blockieren.</p>`;
 search.closest('.searchbox').before(box);box.querySelector('form').addEventListener('submit',e=>{e.preventDefault();searchProduct(false);});box.querySelector('#finder-online').onclick=()=>searchProduct(true);box.addEventListener('click',e=>{const b=e.target.closest('[data-found],[data-finder-more]');if(!b)return;if(b.hasAttribute('data-finder-more')){limit+=20;render();}else select(matches[Number(b.dataset.found)]);});render();}
function fromOFF(p){if(!/^\d{8,14}$/.test(String(p.code||'')))return null;const f=root.NK_SCANNER.fromOFF(p);f.name=(f.name+(p.quantity?' · '+p.quantity:'')).slice(0,240);f.source='Open Food Facts · Community-Daten · '+new Date().toISOString().slice(0,10);f.catalog={type:'off',code:p.code};f.needsBasisConfirmation=true;return f;}
async function searchProduct(online){const q=document.getElementById('finder-query')?.value.trim();if(!q)return notice('Bitte Produktname, Barcode oder Coop-Link eingeben.');lastQuery=q;limit=20;const gen=++generation,id=profile;
 const current=()=>gen===generation&&id===root.NK_HOUSEHOLD?.id&&!!document.getElementById('finder-results');
 try{
  const isLink=/^https?:\/\//i.test(q);if(isLink){const url=PC.coopURL(q),stored=known().filter(f=>f.sourceUrl&&canonical(f.sourceUrl)===url);if(stored.length&&!online){matches=stored;render();notice('Dieses Produkt ist bereits gespeichert. Du kannst es direkt verwenden.');return;}
   const snapshot=seed.find(f=>f.sourceUrl===url);matches=[];render();notice('Coop-Produktseite wird geprüft …');
   try{const r=await root.NK_HOUSEHOLD.api('link',{url},endpoint);if(!current())return;matches=[r.food];notice('Coop-Produktdeklaration gelesen. Bitte Quelle und Packung vergleichen.');}
   catch(err){if(!current())return;if(snapshot){matches=[snapshot];notice('Live-Abruf derzeit nicht möglich. Für diesen Link liegt ein geprüfter Quellenstand vom '+snapshot.importedAt+' vor – ausdrücklich kein aktueller Live-Abruf.');}else{lastQuery=PC.queryFromURL(url);document.getElementById('finder-query').value=lastQuery;matches=local(lastQuery);notice('Coop erlaubt hier keinen sicher auswertbaren Abruf. Die Produktbezeichnung wurde aus dem Link übernommen. Vorhandene Treffer prüfen oder «Online nach Namen suchen» wählen; das sind keine übernommenen Coop-Werte.');}}
   render();return;
  }
  if(q.length>120)throw Error('Für die Namenssuche bitte höchstens 120 Zeichen verwenden.');
  matches=local(q);render();if(matches.length&&!online){notice(matches.length+' vorhandene Treffer. Bei Bedarf «Online nach Namen suchen» verwenden.');return;}
  if(!navigator.onLine)throw Error('Offline: Vorhandene Produkte bleiben nutzbar. Die externe Suche benötigt Internet.');
  notice('Öffentliche Produktdaten werden gesucht …');const barcode=/^\d{8,14}$/.test(q.replace(/\s/g,''));const r=barcode?await root.NK_HOUSEHOLD.api('barcode',{code:q.replace(/\s/g,'')}):await root.NK_HOUSEHOLD.api('search',{query:q},endpoint);if(!current())return;
  const results=(barcode?[r.product]:r.products||[]).map(fromOFF).filter(Boolean);const seen=new Set(matches.map(f=>f.id));for(const f of results)if(!seen.has(f.id)){matches.push(f);seen.add(f.id);}render();notice(results.length?'Treffer aus Open Food Facts ergänzt. Marke, Variante, Packungsgrösse und Bezugsmenge prüfen.':'Keine weiteren passenden Produkte gefunden. Link, Barcode, Foto oder Packungstext versuchen.');
 }catch(err){if(current())notice(err.message||'Suche nicht möglich.');}}
function openFood(f){root.NK_APP.openFood(f);}
function select(f){if(!f)return;const existing=duplicates(f);if(existing.length){if(known().some(x=>x.id===f.id)){openFood(existing[0]);return;}notice('Bereits im Haushalt gespeichert: '+existing[0].name+'. Die vorhandene Vorlage wird verwendet; für abweichende Packungen eine Variante anlegen.');openFood(existing[0]);return;}
 const draft=C.clone(f);draft.n=Object.fromEntries(root.NK_DATA.nutrients.map(n=>[n.key,Number.isFinite(f.n[n.key])?f.n[n.key]:null]));draft.kind='custom';root.NK_APP.reviewFood(draft);const form=document.getElementById('custom-food-form');if(!form)return;
 const note=document.createElement('div');note.className='notice';note.innerHTML='<b>Gefundene Angaben vor dem Speichern prüfen</b><p>'+E(f.sourceSnapshot?'Gespeicherter, geprüfter Quellenstand vom '+f.importedAt+', nicht live aktualisiert.':f.source||'Öffentliche Produktdaten')+'</p>'+(f.sourceUrl?'<a href="'+E(f.sourceUrl)+'" target="_blank" rel="noopener noreferrer">Originalquelle öffnen</a>':'');form.prepend(note);
 const basis=form.querySelector('#custom-basis');if(f.needsBasisConfirmation){basis.insertAdjacentHTML('afterbegin','<option value="">Bitte Packungsspalte wählen</option>');basis.value='';basis.required=true;}
 const label=document.createElement('label');label.className='check';label.innerHTML='<input type="checkbox" required> Produktvariante, Ausgangswerte und 100-g-/100-ml-Bezugsmenge kontrolliert.';form.querySelector('.modal-foot').before(label);
}
let queued=false;const observer=new MutationObserver(()=>{if(!queued){queued=true;queueMicrotask(()=>{queued=false;mount();});}});observer.observe(document.getElementById('app'),{subtree:true,childList:true,attributes:true,attributeFilter:['hidden']});document.addEventListener('nk-profile-loaded',mount);root.NK_FINDER={local,canonical,fromOFF};mount();
})(window);
