'use strict';
const assert=require('node:assert/strict'),C=require('../core.js'),D=(()=>{const w={};require('node:vm').runInNewContext(require('node:fs').readFileSync(require('node:path').join(__dirname,'../data.js'),'utf8'),{window:w});return w.NK_DATA;})();
const keys=D.nutrients.map(n=>n.key);let passed=0;const test=(name,fn)=>{fn();passed++;console.log('PASS',name);};const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
// Artificial test fixtures are used only in tests, never included in the production food database.
const potato={id:'test-potato',name:'Test potato',basis:'g',density:null,n:Object.fromEntries(keys.map(k=>[k,null]))};Object.assign(potato.n,{energy:80,protein:2,vitC:10,vitD:0});
const milk={id:'test-milk',name:'Test protein milk',basis:'ml',density:1.03,n:{...potato.n,protein:6,energy:50,vitC:null}};
const fat={id:'test-fat',name:'Test margarine',basis:'g',density:null,n:{...potato.n,protein:0,energy:720,vitC:0}};
test('full official import 1246 unique IDs',()=>{assert.equal(D.foods.length,1246);assert.equal(new Set(D.foods.map(f=>f.id)).size,1246);assert.equal(D.meta.counts.generic,1216);assert.equal(D.meta.counts.brand,30);});
test('comma decimal',()=>near(C.number('0,5'),.5));
test('empty is not zero',()=>{assert.equal(C.number('',{optional:true}),null);assert.throws(()=>C.number(''));assert.equal(C.number('0'),0);});
test('reject negatives NaN and Infinity',()=>['-1','NaN','Infinity','1e10','<0.2'].forEach(v=>assert.throws(()=>C.number(v))));
test('0.5 dl equals 50 ml',()=>near(C.factor(milk,.5,'dl'),.5));
test('1 l equals 1000 ml',()=>near(C.factor(milk,1,'l'),10));
test('0.25 kg equals 250 g',()=>near(C.factor(potato,.25,'kg'),2.5));
test('volume to mass uses density',()=>near(C.factor({...milk,basis:'g'},50,'ml'),.515));
test('mass to volume uses density',()=>near(C.factor(milk,103,'g'),1));
test('unknown density is error',()=>assert.throws(()=>C.factor(potato,50,'ml'),/Dichte/));
test('user density overrides only conversion',()=>near(C.factor(potato,.5,'dl',1.02),.51));
test('numeric zero known',()=>{const s=C.snapshot(potato,250,'g',null,keys);assert.equal(s.vitD.value,0);assert.equal(s.vitD.known,1);});
test('missing remains unknown',()=>{const s=C.snapshot(potato,250,'g',null,keys);assert.equal(s.calcium.value,null);assert.equal(s.calcium.known,0);});
const recipe={id:'test-recipe',name:'Test mash',servings:2,finalWeight:250,ingredients:[{food:potato,quantity:200,unit:'g'},{food:fat,quantity:10,unit:'g'},{food:milk,quantity:.5,unit:'dl'}]};
test('recipe ingredient sum',()=>near(C.recipeTotal(recipe,keys).protein.value,7));
test('finished weight is denominator only',()=>near(C.recipePortion(recipe,250,'g',keys).protein.value,7));
test('125g from 250g batch is half',()=>near(C.recipePortion(recipe,125,'g',keys).protein.value,3.5));
test('one of two servings',()=>near(C.recipePortion(recipe,1,'portion',keys).protein.value,3.5));
test('ingredient mass is not final weight',()=>near(C.recipeWeight(recipe),261.5));
test('unconfirmed final weight rejected for grams',()=>assert.throws(()=>C.recipePortion({...recipe,finalWeight:null},125,'g',keys)));
test('missing constituent is not silently complete',()=>{const s=C.recipeTotal(recipe,keys);assert.equal(s.vitC.value,20);assert.equal(s.vitC.known,2);assert.equal(s.vitC.total,3);});
test('snapshot does not mutate',()=>{const r=C.clone(recipe),s=C.recipePortion(r,1,'portion',keys);r.ingredients[0].quantity=500;near(s.protein.value,3.5);near(C.recipePortion(r,1,'portion',keys).protein.value,6.5);});
test('empty sum is unknown, not zero intake',()=>assert.equal(C.aggregate([],keys).energy.value,null));
test('0 or negative portions rejected',()=>[0,-1].forEach(n=>assert.throws(()=>C.recipePortion(recipe,n,'portion',keys))));
test('year-month-day validation',()=>{assert.ok(C.validDate('2026-09-26'));assert.ok(!C.validDate('2026-02-30'));assert.ok(!C.validDate('26.09.2026'));});
test('unlogged days excluded from average',()=>{const s=C.initial();s.entries=[{date:'2026-09-24',n:C.snapshot(potato,100,'g',null,keys)},{date:'2026-09-26',n:C.snapshot(potato,200,'g',null,keys)}];const h=C.history(s,'2026-09-26',7,keys);assert.equal(h.days,2);near(h.average.energy.value,120);});
test('complete-only excludes unfinished days',()=>{const s=C.initial();s.entries=[{date:'2026-09-25',n:C.snapshot(potato,100,'g',null,keys)},{date:'2026-09-26',n:C.snapshot(potato,200,'g',null,keys)}];s.days['2026-09-26']={complete:true};const h=C.history(s,'2026-09-26',7,keys,true);assert.equal(h.days,1);near(h.average.energy.value,160);});
const profile={...C.initial().profile,age:40,sex:'m',weight:70,height:175};
test('adult protein weight rule',()=>near(C.targets(profile).values.protein.value,56));
test('65-year age boundary',()=>near(C.targets({...profile,age:65}).values.protein.value,70));
test('micronutrients not scaled with weight',()=>near(C.targets({...profile,weight:72}).values.magnesium.value,350));
test('female magnesium current estimate',()=>near(C.targets({...profile,sex:'w'}).values.magnesium.value,300));
test('protein overweight not full actual weight',()=>assert.equal(C.targets({...profile,weight:100}).values.protein,undefined));
test('explicit calculation weight',()=>near(C.targets({...profile,weight:100,calcWeight:70}).values.protein.value,56));
test('under19 no adult automatic targets',()=>assert.deepEqual(C.targets({...profile,age:18}).values,{}));
test('special situation no ordinary targets',()=>assert.deepEqual(C.targets({...profile,special:true}).values,{}));
test('manual override clear',()=>{const r=C.targets({...profile,manual:{protein:90}}).values.protein;near(r.value,90);assert.equal(r.type,'Eigenes Ziel');});
test('no sex-dependent inference',()=>assert.equal(C.targets({...profile,sex:''}).values.vitC,undefined));
test('vitaminE latest 8mg',()=>near(C.targets(profile).values.vitE.value,8));
test('iodine latest 150µg',()=>near(C.targets(profile).values.iodine.value,150));
test('phosphorus latest 550mg',()=>near(C.targets(profile).values.phosphorus.value,550));
test('folate incompatible equivalent suppressed',()=>assert.ok(C.targets(profile).values.folate.noPercent));
test('zinc unspecified no arbitrary middle',()=>assert.equal(C.targets(profile).values.zinc,undefined));
test('zinc high phytate men',()=>near(C.targets({...profile,phytate:'high'}).values.zinc.value,16));
test('backup full roundtrip',()=>{const s=C.initial();s.recipes=[recipe];s.foods=[potato];s.entries=[{id:'e',date:'2026-09-26',name:'test',meal:1,n:C.recipeTotal(recipe,keys)}];const loaded=C.validateState(JSON.parse(JSON.stringify(s)),keys);near(loaded.entries[0].n.protein.value,7);});
test('bad backup does not pass',()=>assert.throws(()=>C.validateState({schema:99},keys)));
test('negative backup nutrient rejected',()=>{const s=C.initial();s.foods=[{...potato,n:{protein:-1}}];assert.throws(()=>C.validateState(s,keys));});
console.log(JSON.stringify({passed},null,2));
test('malformed calendar month returns false',()=>assert.equal(C.validDate('2026-99-99'),false));
test('HTML in imported ID rejected',()=>{const s=C.initial();s.foods=[{...potato,id:'x\" onclick=\"alert(1)'}];assert.throws(()=>C.validateState(s,keys));});
test('unknown nutrient history remains flagged',()=>{const s=C.initial();s.entries=[{date:'2026-09-25',n:C.snapshot(milk,100,'ml',null,keys)},{date:'2026-09-26',n:C.snapshot(potato,100,'g',null,keys)}];const h=C.history(s,'2026-09-26',7,keys);assert.equal(h.average.vitC.known,1);assert.equal(h.average.vitC.total,2);assert.ok(h.average.vitC.missing.length);});
console.log('TOTAL PASSED',passed);
