'use strict';
const assert=require('node:assert/strict'),U=require('../cup-measures.js'),R=require('../recipe-text-core.js'),C=require('../core.js'),P=require('../product-portions.js');let count=0;
const test=(name,f)=>{f();count++;console.log('PASS',name);},near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,a+' != '+b);
const food={id:'test-flour',name:'Testmehl',basis:'g',n:{energy:360,protein:10,vitC:null},cup:{grams:120,ml:240},density:null},drink={id:'test-drink',name:'Testdrink',basis:'ml',n:{energy:50,protein:5,vitC:null}};
for(const [v,n] of [['½',.5],['⅓',1/3],['⅔',2/3],['1½',1.5],['1 1/2',1.5],['0,5',.5],['3/4',.75],['1/3',1/3],['1',1]])test('Quantity '+v,()=>near(U.amount(v),n));
for(const v of ['','-1','0','1/0','abc','Infinity','NaN','1-2','2/3/4','1e4'])test('Reject quantity '+v,()=>assert.throws(()=>U.amount(v)));
test('240ml cup of drink',()=>near(C.factor(drink,1,'cup240'),2.4));
test('250ml cup of drink',()=>near(C.factor(drink,1,'cup250'),2.5));
test('US cup of drink',()=>near(C.factor(drink,1,'cupUS'),2.365882365));
test('Flour differs from volume',()=>near(C.factor(food,1,'cup240'),1.2));
test('Metric cup weight uses declared filling ratio',()=>near(C.factor(food,1,'cup250'),1.25));
test('Fractional cups',()=>near(C.factor(food,'½','cup240'),.6));
test('Plain grams accept fractions',()=>near(C.factor(food,'1/2','g'),.005));
test('Known density supported',()=>near(C.factor({...food,cup:null,density:.5},1,'cup240'),1.2));
test('Missing density fails rather than assuming water',()=>assert.throws(()=>C.factor({...food,cup:null},1,'cup240'),/Gramm/));
test('Explicit zero density rejected',()=>assert.throws(()=>C.factor({...food,cup:null},1,'cup240',0)));
test('Invalid cup does not validate',()=>assert.throws(()=>U.validate({...food,cup:{grams:-1,ml:240}})));
test('Weight cup requires g basis',()=>assert.throws(()=>U.validate({...food,basis:'ml'})));
test('Cups keep missing vitamins unknown',()=>assert.equal(C.snapshot(food,'1/2','cup240',null,['vitC']).vitC.value,null));
const item={food,quantity:.5,unit:'cup240',density:null},can=U.canonical(P.canonical(item));
test('Saved recipe quantity remains old-client-compatible',()=>{assert.equal(can.unit,'g');near(can.quantity,60);});
test('Editing can restore cup quantity',()=>{const restored=U.hydrate(P.hydrate(can));assert.equal(restored.unit,'cup240');near(restored.quantity,.5);});
test('Broken cup metadata never changes saved quantity',()=>{const x=U.hydrate({...can,quantity:70});assert.equal(x.unit,'g');assert.equal(x.quantity,70);});
test('Changed snapshot weight does not resurrect stale cup amount',()=>{const x=U.hydrate({...can,food:{...food,cup:{grams:180,ml:240}}});assert.equal(x.unit,'g');});
test('Total equals normalized representation',()=>near(C.recipeTotal({ingredients:[item]},['protein']).protein.value,C.recipeTotal({ingredients:[can]},['protein']).protein.value));
test('Scaled entry keeps cup display and canonical amount',()=>{const e=U.entryAmount(food,.5,'cup240'),r=U.scaledEntry(e,2);near(r.amountSpec.quantity,120);assert.equal(r.cupUse.quantity,1);});
test('Regular entries unaffected',()=>assert.equal(U.scaledEntry({amountSpec:{quantity:1,unit:'g'}},2),null));
test('No input mutations',()=>{const b=JSON.stringify(item);U.canonical(item);C.snapshot(food,1,'cup240',null,['protein']);assert.equal(JSON.stringify(item),b);});
const text='Test Pancakes\nFür 2 Portionen\nZutaten:\n1 cup Haferflocken\n200 ml Milch\n2 Eier\nZubereitung:\n1. Alles mischen.\n2. Für 10 Minuten backen.\nNährwerte: 900 kcal';const r=R.parse(text);
test('Whole recipe includes title',()=>assert.equal(r.name,'Test Pancakes'));
test('Servings detected',()=>assert.equal(r.servings,'2'));
test('No preparation numbers imported as food',()=>assert.equal(r.ingredients.length,3));
test('Original preserved byte for byte',()=>assert.equal(r.original,text));
test('Preparation preserved',()=>assert.ok(r.notes.includes('10 Minuten')));
test('Numeric claims in preparation not used',()=>assert.equal(r.ingredients.find(x=>x.name.includes('kcal')),undefined));
test('English ingredients and directions',()=>{const x=R.parse('Porridge\nServings: 2\nIngredients\n½ cup oats\n1 1/2 cups milk\nDirections\nStir.');assert.equal(x.ingredients[1].quantity,'1.5');assert.equal(x.servings,'2');});
test('Egg number becomes piece with warning',()=>{assert.equal(r.ingredients[2].unit,'piece');assert.ok(r.ingredients[2].warning);});
test('Comma decimals',()=>assert.equal(R.line('1,5 dl Milch').quantity,'1.5'));
test('No space between amount and unit',()=>assert.equal(R.line('250g Mehl').unit,'g'));
test('Tablespoon marked separately',()=>assert.equal(R.line('2 EL Öl').unit,'tbsp'));
test('Teaspoon marked separately',()=>assert.equal(R.line('1 tsp Salz').unit,'tsp'));
test('Unknown quantity not guessed',()=>assert.equal(R.line('Salz nach Geschmack').quantity,''));
test('Unknown pack quantity not treated as gram weight',()=>{const x=R.line('1 Dose Bohnen');assert.equal(x.unit,'');assert.ok(x.warning);});
test('Pack multiplication explicit',()=>assert.equal(R.line('2 x 400 g Tomaten').quantity,'800'));
test('Range remains unresolved',()=>{const x=R.line('2–3 EL Öl');assert.equal(x.quantity,'');assert.equal(x.unit,'tbsp');});
test('German ingredient heading can carry portion count',()=>assert.equal(R.parse('Rezept\nZutaten für 4 Personen:\n100 g Mehl\nZubereitung\nBacken').servings,'4'));
test('No headings stays explicitly uncertain',()=>assert.ok(R.parse('Porridge\n100 g Haferflocken\n200 ml Milch').warnings.length));
test('Ingredient without name requires selection later',()=>assert.equal(R.line('100 g').name,'100 g'));
test('Pasted HTML remains plain text',()=>{const s='<img src=x onerror=alert(1)>\nZutaten:\n1 g Salz';assert.ok(R.parse(s).name.includes('<img'));});
test('Too-large input rejected, not silently trimmed',()=>assert.throws(()=>R.parse('x'.repeat(30001))));
test('Empty input rejected',()=>assert.throws(()=>R.parse('')));
test('No ingredients rejected',()=>assert.throws(()=>R.parse('Hello')));
test('Max 200 ingredient lines',()=>assert.throws(()=>R.parse('Zutaten\n'+('1g Salz\n'.repeat(201)))));
console.log('TOTAL CUPS/RECIPE TESTS',count);
