'use strict';
const assert=require('node:assert/strict'),R=require('../day-review-core.js'),C=require('../core.js'),S=require('../sync-core.js');
let passed=0;function test(name,f){f();passed++;console.log('PASS',name);}
const base=C.initial(),today='2026-09-28',day='2026-09-27';const sample=()=>({...C.clone(base),entries:[{id:'old',date:'2026-09-26'},{id:'yesterday',date:day},{id:'today',date:today}]});
test('Previous calendar day',()=>assert.equal(R.previousDay(today),day));
test('Month boundary',()=>assert.equal(R.previousDay('2026-10-01'),'2026-09-30'));
test('Year boundary',()=>assert.equal(R.previousDay('2027-01-01'),'2026-12-31'));
test('Leap day',()=>assert.equal(R.previousDay('2024-03-01'),'2024-02-29'));
test('Non leap year',()=>assert.equal(R.previousDay('2026-03-01'),'2026-02-28'));
test('DST spring transition',()=>assert.equal(R.previousDay('2026-03-30'),'2026-03-29'));
test('DST autumn transition',()=>assert.equal(R.previousDay('2026-10-26'),'2026-10-25'));
test('Reject invalid dates',()=>{for(const d of ['2026-02-30','2026-13-01','2026-9-01','today',null,{},'2026-09-28T00:00'])assert.throws(()=>R.previousDay(d));});
test('Only unfinished yesterday with entries is eligible',()=>assert.deepEqual(R.candidate(sample(),today),{date:day,count:1}));
test('New empty profile is not nagged',()=>assert.equal(R.candidate(base,today),null));
test('Today or older entries alone do not count',()=>{const s=sample();s.entries=s.entries.filter(e=>e.date!==day);assert.equal(R.candidate(s,today),null);});
test('Complete yesterday is skipped',()=>{const s=sample();s.days[day]={complete:true};assert.equal(R.candidate(s,today),null);});
test('An explicit no also prevents repetition for the same day',()=>{const s=sample();s.profile.dayReviewThrough=day;assert.equal(R.candidate(s,today),null);});
test('Next day becomes eligible',()=>{const s=sample();s.profile.dayReviewThrough=day;assert.deepEqual(R.candidate(s,'2026-09-29'),{date:today,count:1});});
test('Invalid seen marker does not disable reminder',()=>{const s=sample();s.profile.dayReviewThrough='not-a-date';assert.ok(R.candidate(s,today));});
test('Candidate never changes diary',()=>{const s=sample(),before=JSON.stringify(s);R.candidate(s,today);assert.equal(JSON.stringify(s),before);});
test('Signature ignores entry ordering',()=>{const s=sample(),b=C.clone(s);b.entries.reverse();assert.equal(R.signature(s,day,S.stable),R.signature(b,day,S.stable));});
test('Signature detects edited yesterday',()=>{const s=sample(),b=C.clone(s);b.entries[1].name='changed';assert.notEqual(R.signature(s,day,S.stable),R.signature(b,day,S.stable));});
test('Signature ignores unrelated dates',()=>{const s=sample(),b=C.clone(s);b.entries[2].name='changed';assert.equal(R.signature(s,day,S.stable),R.signature(b,day,S.stable));});
test('Highest valid calendar marker',()=>assert.equal(R.highest('2026-02-30',day,today,null),today));
test('Profile validation drops malformed marker',()=>{const s=C.clone(base);s.profile.dayReviewThrough={bad:true};assert.deepEqual(C.validateState(s,[]),base);});
test('Profile validation preserves valid marker',()=>{const s=C.clone(base);s.profile.dayReviewThrough=day;assert.equal(C.validateState(s,[]).profile.dayReviewThrough,day);});
test('Monotone marker merges without a false conflict',()=>{const l=C.clone(base),r=C.clone(base);l.profile.dayReviewThrough=day;r.profile.dayReviewThrough=today;const m=S.merge(base,l,r);assert.equal(m.conflicts.length,0);assert.equal(m.state.profile.dayReviewThrough,today);});
test('Older client cannot drop reminder response',()=>{const b=C.clone(base),l=C.clone(base),r=C.clone(base);b.profile.dayReviewThrough=day;l.profile.dayReviewThrough=today;assert.equal(S.merge(b,l,r).state.profile.dayReviewThrough,today);});
test('Unrelated fields and explicit user conflicts remain intact',()=>{const l=C.clone(base),r=C.clone(base);l.profile.weight=80;r.profile.weight=81;l.profile.dayReviewThrough=day;const m=S.merge(base,l,r);assert.deepEqual(m.conflicts,['profile.weight']);assert.equal(m.state.profile.dayReviewThrough,day);});
console.log('TOTAL DAY REVIEW TESTS',passed);
