'use strict';const assert=require('node:assert/strict'),C=require('../core.js'),M=require('../food-portions.js'),S=require('../food-search.js');global.window=global;require('../data.js');const D=NK_DATA,keys=D.nutrients.map(x=>x.key);let checks=0;function test(n,f){f();checks++;console.log('PASS',n)}
const food={id:'test-food',name:'Test',basis:'g',density:null,n:Object.fromEntries(keys.map(k=>[k,k==='protein'?10:k==='energy'?200:k==='sugar'?0:null])),portion:{label:'Riegel',amount:30,unit:'g'}};
test('piece gram factor',()=>assert.equal(C.factor(food,2,'piece'),.6));
test('decimal comma piece count',()=>assert.equal(C.factor(food,'0,5','piece'),.15));
test('piece nutrition total',()=>assert.equal(C.snapshot(food,2,'piece',null,keys).protein.value,6));
test('unknown stays unknown',()=>assert.equal(C.snapshot(food,2,'piece',null,keys).vitD.value,null));
test('true zero remains zero',()=>assert.equal(C.snapshot(food,2,'piece',null,keys).sugar.value,0));
test('ml cup uses volume, not assumed density',()=>assert.equal(C.factor({...food,basis:'ml',portion:{label:'Becher',amount:250,unit:'ml'}},.5,'piece'),1.25));
test('missing portion refuses count',()=>assert.throws(()=>C.factor({...food,portion:null},1,'piece')));
test('mismatched weight and volume refuses',()=>assert.throws(()=>C.factor({...food,portion:{...food.portion,unit:'ml'}},1,'piece')));
for(const q of [0,-1,Infinity,'bad',''])test('invalid count '+q,()=>assert.throws(()=>C.factor(food,q,'piece')));
for(const amount of [0,-1,100001,Infinity,'30'])test('invalid portion '+amount,()=>assert.throws(()=>C.validateFood({...food,portion:{...food.portion,amount}},keys)));
test('label length validated',()=>assert.throws(()=>C.validateFood({...food,portion:{...food.portion,label:'a'.repeat(41)}},keys)));
test('recipe stores normalized units',()=>{const i=M.ingredient(food,2,'piece',null);assert.equal(i.quantity,60);assert.equal(i.unit,'g');assert.equal(i.piece.count,2)});
test('recipe fraction retained',()=>assert.deepEqual(M.selection(M.ingredient(food,.5,'piece',null)),{quantity:.5,unit:'piece'}));
test('inconsistent metadata cannot change actual grams',()=>assert.deepEqual(M.selection({...M.ingredient(food,2,'piece',null),quantity:100}),{quantity:100,unit:'g'}));
test('g to piece is reversible',()=>assert.equal(M.convertQuantity(food,60,'g','piece'),2));
test('piece to kg converts quantity',()=>assert.equal(M.convertQuantity(food,2,'piece','kg'),.06));
test('unknown density never imputed',()=>assert.throws(()=>M.convertQuantity(food,2,'piece','ml')));
test('explicit density used when changing units',()=>assert.equal(M.convertQuantity(food,2,'piece','ml',1.2),50));
test('edit piece quantity',()=>{const i=M.ingredient(food,2,'piece');M.edit(i,'quantity','1,5');assert.equal(i.quantity,45);assert.equal(i.piece.count,1.5)});
test('edit normalized units',()=>{const i=M.ingredient(food,2,'piece');M.edit(i,'unit','kg');assert.equal(i.quantity,.06);assert.equal(i.piece,undefined)});
test('recipe total and final weight use actual amounts',()=>{const r={servings:2,ingredients:[M.ingredient(food,2,'piece',null)]};assert.equal(C.recipeWeight(r),60);assert.equal(C.recipePortion(r,1,'portion',keys).protein.value,3)});
test('backup round trips pieces',()=>{const st=C.initial();st.foods=[food];st.recipes=[{id:'r',name:'R',servings:1,ingredients:[M.ingredient(food,2,'piece',null)]}];const next=C.validateState(st,keys);assert.equal(next.foods[0].portion.amount,30);assert.equal(next.recipes[0].ingredients[0].piece.count,2)});
test('snapshot stays unchanged after portion edit',()=>{const f=C.clone(food),n=C.snapshot(f,2,'piece',null,keys);f.portion.amount=50;assert.equal(n.protein.value,6)});
test('no metadata on older foods stays valid',()=>C.validateFood({...food,portion:undefined},keys));
const raw=JSON.stringify(D.foods.map(f=>[f.id,f.n,f.q]));const enhanced=S.enrich(D.foods);
test('many basic foods gain aliases without duplicating records',()=>assert.ok(enhanced>30));
test('exact nutrient data and IDs unchanged',()=>assert.equal(raw,JSON.stringify(D.foods.map(f=>[f.id,f.n,f.q]))));
test('Ei search has actual eggs at top',()=>assert.deepEqual(S.search(D.foods,'Ei').slice(0,2).map(x=>x.id),['blv-290','blv-1070']));
test('Eier includes whole eggs',()=>assert.ok(S.search(D.foods,'Eier').slice(0,2).every(x=>['blv-290','blv-1070'].includes(x.id))));
test('hartgekochtes Ei finds cooked whole egg',()=>assert.equal(S.search(D.foods,'hartgekochtes Ei')[0].id,'blv-1070'));
test('Ei does not match unrelated substring',()=>assert.ok(!S.search(D.foods,'Ei').some(x=>x.name.startsWith('Reis,'))));
test('egg white is not whole egg',()=>assert.equal(S.search(D.foods,'Eiklar')[0].id,'blv-411'));
test('German umlaut variant finds existing foods',()=>assert.ok(S.search(D.foods,'Ruebli').length>0));
console.log('TOTAL PIECE & SEARCH TESTS',checks,'; alias-enriched foods',enhanced);
