'use strict';
const assert=require('node:assert/strict');global.window=global;require('../data.js');const C=require('../core.js');global.NK=C;const P=global.NK_PORTIONS=require('../portion-normalizer.js'),S=require('../scanner.js'),F=require('../food-discovery.js');
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS',name);},near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
test('Ei returns cooked and raw whole eggs first',()=>assert.deepEqual(F.search(NK_DATA.foods,'Ei').slice(0,2).map(x=>x.id),['blv-1070','blv-290']));
test('Eier plural returns both whole eggs',()=>assert.deepEqual(F.search(NK_DATA.foods,'Eier').slice(0,2).map(x=>x.id),['blv-1070','blv-290']));
test('Specific egg preparation respected',()=>assert.equal(F.search(NK_DATA.foods,'Ei roh')[0].id,'blv-290'));
test('Short Ei query no incidental Reis or Fleisch',()=>assert.ok(!F.search(NK_DATA.foods,'Ei').some(f=>/^Reis |^Fleisch/i.test(f.name))));
test('German transliteration finds Huehnerei',()=>assert.equal(F.search(NK_DATA.foods,'huehnerei')[0].id,'blv-1070'));
test('Scrambled eggs rank before other dishes',()=>assert.equal(F.search(NK_DATA.foods,'Rührei')[0].id,'blv-1602'));
test('Eiklar and Eidotter distinct',()=>{assert.equal(F.search(NK_DATA.foods,'Eiklar')[0].id,'blv-411');assert.equal(F.search(NK_DATA.foods,'Eidotter')[0].id,'blv-410');});
test('Seidentofu common term',()=>assert.equal(F.search(NK_DATA.foods,'Seidentofu')[0].id,'blv-13438'));
test('Search never mutates source dataset',()=>{const before=JSON.stringify(NK_DATA.foods);F.search(NK_DATA.foods,'Ei');assert.equal(JSON.stringify(NK_DATA.foods),before);});
test('Custom products names supported',()=>assert.equal(F.search([{name:'Mein Brot',id:'custom-me',n:{}}],'Mein Brot').length,1));
test('Barcode metadata searched',()=>assert.equal(F.search([{name:'Product',id:'off-12345678',catalog:{code:'12345678'}}],'12345678').length,1));
const single='pro 30 g Energie 150 kcal Fett 9 g davon gesättigte Fettsäuren 1 g Kohlenhydrate 12 g davon Zucker 0 g Nahrungsfasern 0,9 g Eiweiss 3 g Salz 0,2 g Vitamin B12 0,3 µg';
test('All single-line nutrient labels parsed',()=>{const n=S.parse(single).n;assert.equal(n.energy,150);assert.equal(n.fat,9);assert.equal(n.saturated,1);assert.equal(n.carbs,12);assert.equal(n.sugar,0);assert.equal(n.protein,3);assert.equal(n.fiber,.9);assert.equal(n.salt,.2);assert.equal(n.vitB12,.3);});
test('Single-line grams normalize correctly',()=>{const n=P.convert(S.parse(single).n,{},30,'g').n;near(n.protein,10);near(n.vitB12,1);near(n.fiber,3);});
test('Tab separated name value unit',()=>assert.equal(S.parse('pro 100 g\nEiweiss\t26\tg\nFett\t6,6 g').n.protein,26));
test('Nutrient label and following value line',()=>assert.equal(S.parse('pro 100 g\nEiweiss\n26 g').n.protein,26));
test('Semicolon and colon formats',()=>{const n=S.parse('pro 100g; Eiweiss: 3g; Fett: 2g; Kohlenhydrate: 5g').n;assert.equal(n.protein,3);assert.equal(n.fat,2);assert.equal(n.carbs,5);});
test('Micronutrients keep original compatible units',()=>{const n=S.parse('Vitamin B12 0,3 µg; Calcium 20 mg; Eisen 0,6 mg').n;near(n.vitB12,.3);near(n.calcium,20);near(n.iron,.6);});
test('Reference intake footer does not override calories',()=>assert.equal(S.parse('Energie 500 kcal\nReferenzmenge für Erwachsene 8400 kJ / 2000 kcal').n.energy,500));
test('Missing unit not invented',()=>assert.equal(S.parse('Eiweiss 26').n.protein,undefined));
test('Empty or marketing text not a fabricated table',()=>assert.deepEqual(S.parse('Vegetarisch, lecker und proteinreich').n,{}));
test('HTML-looking pasted content is data only',()=>{assert.equal(S.parse('<img src=x onerror=alert(1)>\nEiweiss 3 g').n.protein,3);});
test('Less-than remains unknown',()=>{const s=S.parse('Zucker <0,5 g');const r=P.convert(s.n,s.q,50,'g');assert.equal(r.n.sugar,null);assert.match(r.q.sugar,/< 1 g/);});
test('New declarations preserve original base',()=>{const before=JSON.stringify(NK_DATA.foods);require('../everyday-foods.js');assert.equal(NK_EVERYDAY.added,2);assert.equal(JSON.stringify(NK_DATA.foods.slice(0,-2)),before);});
test('New entries have complete nutrient keys and sources',()=>{for(const f of NK_DATA.foods.slice(-2)){C.validateFood(f,NK_DATA.nutrients.map(n=>n.key));assert.equal(Object.keys(f.n).length,NK_DATA.nutrients.length);assert.ok(f.source.includes('27.09.2026'));assert.equal(f.n.vitB12,null);}});
test('New yeast is found by Nährhefe',()=>assert.equal(F.search(NK_DATA.foods,'Nährhefe')[0].id,'label-koro-yeast-flakes'));
test('No hidden duplicate additions on load',()=>{const total=NK_DATA.foods.length;delete require.cache[require.resolve('../everyday-foods.js')];require('../everyday-foods.js');assert.equal(NK_DATA.foods.length,total);});
console.log('TOTAL FOOD ENTRY TESTS',count);
