'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const SEARCH=require('../food-search.js'),P=require('../portion-normalizer.js');global.NK_PORTIONS=P;const S=require('../scanner.js');
const ctx={console,URL};ctx.window=ctx;vm.createContext(ctx);for(const f of ['data.js','macro-goals.js','core.js','veggie-data.js','catalog.js'])vm.runInContext(fs.readFileSync(__dirname+'/../'+f,'utf8'),ctx);
const original=JSON.stringify(ctx.NK_DATA.foods),before=ctx.NK_DATA.foods.length;
vm.runInContext(fs.readFileSync(__dirname+'/../additional-foods.js','utf8'),ctx);
const foods=ctx.NK_DATA.foods,eggIds=['blv-290','blv-1070'];
let count=0;const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
function test(name,fn){fn();count++;console.log('PASS',name);}
test('egg query promotes whole raw and cooked eggs',()=>assert.deepEqual(new Set(SEARCH.ranked(foods,'Ei').slice(0,2).map(x=>x.id)),new Set(eggIds)));
test('egg query does not match Reis or Eis',()=>assert.ok(SEARCH.ranked(foods,'Ei').every(f=>!/^Reis|^Eis/i.test(f.name))));
test('plural eggs',()=>assert.ok(eggIds.includes(SEARCH.ranked(foods,'Eier')[0].id)));
test('cooked egg exact variant',()=>assert.equal(SEARCH.ranked(foods,'gekochtes Ei')[0].id,'blv-1070'));
test('raw egg exact variant',()=>assert.equal(SEARCH.ranked(foods,'rohes Ei')[0].id,'blv-290'));
test('German keyboard transliteration',()=>assert.ok(eggIds.includes(SEARCH.ranked(foods,'Huehnerei')[0].id)));
test('English egg search',()=>assert.ok(eggIds.includes(SEARCH.ranked(foods,'egg')[0].id)));
test('egg white does not mean every high-protein food',()=>assert.equal(SEARCH.ranked(foods,'Eiklar')[0].id,'blv-411'));
test('egg yolk',()=>assert.equal(SEARCH.ranked(foods,'Eigelb')[0].id,'blv-410'));
test('pasta alias finds existing cooked pasta',()=>assert.ok(SEARCH.ranked(foods,'Nudeln gekocht').some(f=>f.id==='blv-1063')));
test('broccoli spelling',()=>assert.equal(SEARCH.ranked(foods,'Brokkoli')[0].id,'blv-351'));
test('magerquark alias',()=>assert.equal(SEARCH.ranked(foods,'Magerquark')[0].id,'blv-71'));
test('no cooked fried-egg values invented',()=>assert.equal(SEARCH.ranked(foods,'Spiegelei').length,0));
test('search deduplicates by id with first preference',()=>assert.equal(SEARCH.ranked([foods[0],foods[0]],'').length,1));
test('search never mutates collection or nutrients',()=>{const before=JSON.stringify(foods);SEARCH.ranked(foods,'Ei');assert.equal(JSON.stringify(foods),before);});
test('eight additional label records',()=>assert.equal(foods.length-before,8));
test('original 1297 records exactly unchanged',()=>assert.equal(JSON.stringify(foods.slice(0,before)),original));
test('new ids are unique',()=>assert.equal(new Set(foods.map(f=>f.id)).size,foods.length));
test('new source URLs present and HTTPS',()=>ctx.NK_ADDITIONAL_FOODS.foods.forEach(f=>assert.ok(f.sourceUrl.startsWith('https://eatplanted.com/products/'))));
test('missing calcium remains unknown in labels',()=>ctx.NK_ADDITIONAL_FOODS.foods.forEach(f=>assert.equal(f.n.calcium,null)));
test('new label exact protein',()=>assert.equal(foods.find(f=>f.id==='label-planted-chicken-natur').n.protein,24));
test('manufacturer label recipe portion calculation',()=>{const f=foods.find(f=>f.id==='label-planted-chicken-natur');near(ctx.NK.snapshot(f,50,'g',null,['protein']).protein.value,12);});
test('loading addendum twice is idempotent',()=>{vm.runInContext(fs.readFileSync(__dirname+'/../additional-foods.js','utf8'),ctx);assert.equal(foods.length,before+8);});
test('Swiss Nahrungsfasern parsed',()=>near(S.parse('Pro 100 g\nNahrungsfasern 4,5 g').n.fiber,4.5));
test('inline pasted macro table parsed',()=>{const n=S.parse('pro 100 g\nEnergie 500 kcal Fett 30 g davon gesättigte Fettsäuren 5 g Kohlenhydrate 50 g davon Zucker 2 g Eiweiss 10 g Salz 1,2 g').n;near(n.energy,500);near(n.fat,30);near(n.saturated,5);near(n.carbs,50);near(n.sugar,2);near(n.protein,10);near(n.salt,1.2);});
test('separate label and value with colon',()=>near(S.parse('pro 100 g\nEiweiss:\n3,4 g').n.protein,3.4));
test('30 gram text rescales once',()=>{const r=S.parse('Pro Portion (30 g)\nEnergie 150 kcal Fett 9 g Eiweiss 3 g');const n=P.convert(r.n,r.q,30,'g').n;near(n.energy,500);near(n.protein,10);});
test('percent RI is not a nutrient quantity',()=>assert.equal(S.parse('Protein 5 %').n.protein,undefined));
test('ingredient list alone does not invent quantities',()=>{const n=S.parse('Zutaten: Kartoffeln, Rapsöl, Salz. Vegan.').n;assert.equal(Object.keys(n).length,0);});
test('micrograms and milligrams normalized',()=>{const n=S.parse('Vitamin B12 0,003 mg Calcium 120 mg').n;near(n.vitB12,3);near(n.calcium,120);});
test('unknown limit not converted to zero',()=>{const n=S.parse('pro 100 g\nFett <0,5 g').n;assert.equal(n.fat,null);});
test('real zero remains known',()=>near(S.parse('pro 100 g\nZucker 0 g').n.sugar,0));
test('choosing last column preserves safety for singleton rows',()=>{const n=S.parse('pro 100 g | pro 30 g\nProtein 10 g\nFett 30 g 9 g','last').n;assert.equal(n.protein,undefined);near(n.fat,9);});
console.log('TOTAL FOOD ENTRY TESTS',count);
