'use strict';
const assert=require('node:assert/strict'),M=require('../household-measures.js'),U=require('../cup-measures.js'),P=require('../product-portions.js'),C=require('../core.js'),fs=require('node:fs'),vm=require('node:vm');
const ctx={};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../data.js'),'utf8'),ctx);
const foods=JSON.parse(JSON.stringify(ctx.NK_DATA.foods)),old=JSON.stringify(foods),count=M.decorate(foods),get=id=>foods.find(f=>f.id==='blv-'+id),test=(name,fn)=>{fn();passed++;console.log('PASS',name);};let passed=0;
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
test('31 exact mapped records decorated',()=>assert.equal(count,31));
test('Source identities unique',()=>assert.equal(new Set(M.data.records.map(r=>r.id)).size,30));
test('All new definitions validate without changing nutrients',()=>{const prev=JSON.parse(old);for(const f of foods){C.validateFood(f,Object.keys(f.n));assert.deepEqual(f.n,prev.find(g=>g.id===f.id).n);}});
test('Existing source nutrient metadata is unchanged',()=>{for(const f of foods)assert.deepEqual(f.q,JSON.parse(old).find(x=>x.id===f.id).q);});
test('Reference values positive and derived from source quantity',()=>{for(const r of M.data.records)for(const v of [...r.cups,...r.pieces]){assert.ok(v.grams>0);close(v.grams,v.sourceGrams/v.sourceAmount);}});
test('Edible medium onion is 110g',()=>assert.equal(get(368).portion.size,110));
test('Two medium onions 220g',()=>close(P.factor(get(368),2)*100,220));
test('Onion small and large reflect real source sizes',()=>{assert.equal(M.choose(get(368),'piece','small').portion.size,70);assert.equal(M.choose(get(368),'piece','large').portion.size,150);});
test('Red and green pepper medium119g',()=>{assert.equal(get(360).portion.size,119);assert.equal(get(359).portion.size,119);});
test('Half medium pepper is59.5g',()=>close(C.factor(get(360),'1/2','piece')*100,59.5));
test('Cups onion chopped160g versus sliced115g',()=>{close(U.factor(get(368),1,'cup240')*100,160);close(U.factor(M.choose(get(368),'cup','sliced'),1,'cup240')*100,115);});
test('Metric cup scales same filling only',()=>close(U.factor(get(368),1,'cup250')*100,160/240*250));
test('US cup uses explicit exact existing volume',()=>close(U.factor(get(368),1,'cupUS')*100,160/240*236.5882365));
test('Material density not overwritten by bulk equivalent',()=>assert.equal(get(368).density,null));
test('White rice raw and cooked separated',()=>{assert.equal(get(427).cup.grams,185);assert.equal(get(1066).cup.grams,158);});
test('Rolled oats are not whole oats',()=>assert.equal(get(198).cup.grams,89));
test('Flour mapped to exact two white flour entries',()=>{assert.equal(get(205).cup.grams,125);assert.equal(get(204).cup.grams,125);});
test('Dry versus cooked quinoa uses separate source values',()=>{assert.equal(get(13394).cup.grams,170);assert.equal(get(13396).cup.grams,185);});
test('Cucumber half cup source correctly normalised',()=>assert.equal(get(354).cup.grams,104));
test('No estimate applied to paprika spice',()=>assert.ok(!get(663).cup&&!get(663).portion));
test('No fuzzy mapping of same name to custom item',()=>{const f={...get(368),id:'custom-test',cup:null,portion:null};assert.equal(M.defaults(f),f);assert.equal(M.record(f),null);});
test('ID/name mismatch never automatically mapped',()=>{const f={...get(368),name:'Zwiebelpulver',cup:null,portion:null};assert.equal(M.defaults(f),f);});
test('Native liquid density not displaced',()=>{const f={...get(368),density:.75,cup:null,portion:null};assert.equal(M.defaults(f).cup,null);assert.equal(M.defaults(f).density,.75);});
test('Own cup remains priority',()=>{const f={...get(368),cup:{grams:123,ml:250}};assert.deepEqual(M.defaults(f).cup,{grams:123,ml:250});});
test('Own portion remains priority',()=>{const f={...get(368),portion:{label:'Mein Stück',size:87,unit:'g'}};assert.equal(M.defaults(f).portion.size,87);});
test('Unchanged references kept through custom editor',()=>assert.equal(M.preserve({label:'Zwiebel',size:110,unit:'g'},get(368).portion,'piece').estimated,true));
test('Own changed weight replaces estimate',()=>assert.equal(M.preserve({label:'Stück',size:80,unit:'g'},get(368).portion,'piece').estimated,undefined));
test('Same cup density retains provenance when cup volume changes',()=>assert.equal(M.preserve({grams:160/240*250,ml:250},get(368).cup,'cup').estimated,true));
test('Fresh estimates never contaminate weighed grams',()=>assert.equal(M.itemEstimated({food:get(368),quantity:110,unit:'g'}),false));
test('Cup diary amount declares approximation',()=>assert.match(U.entryAmount(get(368),1,'cup240').amountText,/ca.*geschätzt/));
test('Piece diary amount declares approximation',()=>assert.match(P.entryAmount(get(368),2,'piece').amountText,/ca.*220.*geschätzt/));
test('Scaling cup diary retains approximation',()=>{const e=U.entryAmount(get(368),1,'cup240');const out=U.scaledEntry(e,.5);assert.match(out.amountText,/80.*geschätzt/);assert.equal(out.cupUse.estimated,true);});
test('Scaling piece diary retains approximation',()=>assert.match(P.scaledEntry(P.entryAmount(get(368),2,'piece'),.5).amountText,/110.*geschätzt/));
test('Canonical recipe cup preserves estimate metadata',()=>{const i=U.canonical(P.canonical({food:get(368),quantity:1,unit:'cup240'}));assert.equal(i.quantity,160);assert.equal(M.itemEstimated(i),true);assert.equal(U.hydrate(i).unit,'cup240');});
test('Canonical recipe piece preserves estimate metadata',()=>{const i=U.canonical(P.canonical({food:get(368),quantity:2,unit:'piece'}));assert.equal(i.quantity,220);assert.equal(M.itemEstimated(i),true);assert.equal(P.hydrate(i).unit,'piece');});
test('Ingredient suggestions use explicit size text',()=>assert.equal(M.suggested(get(368),'piece','2 grosse Zwiebeln'),'large'));
test('Ingredient form suggestion respects available cut',()=>assert.equal(M.suggested(get(368),'cup','1 cup Zwiebel, in Scheiben'),'sliced'));
test('Unknown cut cannot create unsupported reference',()=>assert.throws(()=>M.choose(get(368),'cup','powder')));
test('Snapshot and source immutable when choosing a size',()=>{const f=get(368),before=JSON.stringify(f),n=C.snapshot(f,2,'piece',null,['protein']);M.choose(f,'piece','large');assert.equal(JSON.stringify(f),before);assert.deepEqual(C.snapshot(f,2,'piece',null,['protein']),n);});
test('Historical saved gram ingredients not decorated',()=>{const historical=JSON.parse(old).find(f=>f.id==='blv-368');assert.equal(M.itemEstimated({food:historical,quantity:100,unit:'g'}),false);});
test('Shared explicit reference keeps access to variants',()=>{const f={...get(368),id:'shared-abc',name:'Unsere Zwiebel'};assert.equal(M.options(f,'piece').length,3);});
test('Stale canonical estimate metadata never marks an edited weighed amount',()=>{const i=P.canonical({food:get(368),quantity:1,unit:'piece'});i.quantity=120;assert.equal(M.itemEstimated(i),false);});
console.log('TOTAL HOUSEHOLD MEASURE TESTS',passed);
