'use strict';
const assert=require('node:assert/strict'),I=require('../import-core.js'),G=require('../protein-celebration.js'),C=require('../core.js');
let count=0;const test=(n,f)=>{f();count++;console.log('PASS',n)};
const link='https://www.coop.ch/de/lebensmittel/fleisch-fisch/the-veggie-chef/steaks-filets/redefine-vegane-alternative-zu-flank-steak/p/7451865';
test('Coop tracking stripped and canonical ID kept',()=>{const r=I.normalize(link+'?gclid=secret&x=1#hello');assert.equal(r.key,'coop-7451865');assert.equal(r.url,link)});
for(const x of ['http://127.0.0.1/a','https://localhost/p/111111','https://www.coop.ch.evil.com/p/111111','https://user:pw@www.coop.ch/de/a/p/123456','https://www.coop.ch:8080/de/a/p/123456','https://www.coop.ch/de/a/p/123456%2f../foo','javascript:alert(1)','file:///etc/passwd','https://169.254.169.254'])test('Unsupported or unsafe URL rejected '+x,()=>assert.throws(()=>I.normalize(x)));
test('OFF barcode URL canonicalized',()=>assert.equal(I.normalize('https://world.openfoodfacts.org/product/1234567890123/name?x=1').code,'1234567890123'));
test('Plain name accepted',()=>assert.equal(I.normalize('Redefine Flank Steak').type,'name'));
test('Verified example available by name and link, labelled snapshot',()=>{const p=I.seed('redefine flank steak');assert.equal(p.n.protein,26);assert.equal(p.lookup.mode,'snapshot');assert.equal(I.seed(link).n.vitB12,2.5)});
test('Other products never use example data',()=>assert.equal(I.seed(link.replace('7451865','1234567')),null));
test('OFF unit conversions and unknown versus zero',()=>{const p=I.fromOFF({code:'1234567890123',product_name:'Test',nutriments:{proteins_100g:4,'vitamin-b12_100g':.0000025,sugars_100g:0}});assert.equal(p.n.vitB12,2.5);assert.equal(p.n.sugar,0);assert.equal(p.n.fat,null);assert.equal(p.lookup.basisUncertain,true)});
test('No-nutrition records are rejected',()=>assert.throws(()=>I.fromOFF({code:'1234567890123'})));
const html='<h1>Steak &amp; Test</h1><h2>Durchschnittliche Nährwerte pro:</h2><b>100g</b><ul><li>Energie 790 kJ</li><li>Energie 188 kcal</li><li>Fett 6.6g</li><li>davon gesättigte Fettsäuren 0.8g</li><li>Kohlenhydrate 4g</li><li>davon Zucker 1.9g</li><li>Nahrungsfasern (Ballaststoffe) 4.5g</li><li>Eiweiss 26g</li><li>Salz 0.88g</li><li>Vitamin B12 2.5µg</li></ul><h2>Bewertungen</h2>';
test('Single-column explicit label table parses with units',()=>{const r=I.parseCoop(html,link);assert.equal(r.name,'Steak & Test');assert.equal(r.n.energy,188);assert.equal(r.n.protein,26);assert.equal(r.n.vitB12,2.5)});
test('No arbitrary guessing of energy units',()=>{const r=I.parseCoop(html.replace('790 kJ','790').replace('188 kcal','188'),link);assert.equal(r.n.energy,undefined)});
test('Multiple header columns rejected',()=>assert.throws(()=>I.parseCoop(html.replace('100g','100g / Portion 30g'),link)));
test('Malformed or absent nutrition refuses',()=>assert.throws(()=>I.parseCoop('<h1>Test</h1>',link)));
const today=C.dateKey(),other='2000-01-01',base=C.initial();base.profile.manual={protein:60};
const entry=(id,v,date=today,known=1,total=1)=>({id,date,n:{protein:{value:v,known,total}}});
const state=es=>({...structuredClone(base),entries:es});
test('Goal crossing produces celebration',()=>assert.equal(G.crossing(state([entry('a',50)]),state([entry('a',50),entry('b',10)]),today,C).target,60));
test('First recorded meal can reach goal',()=>assert.ok(G.crossing(state([]),state([entry('a',60)]),today,C)));
test('Below goal is not celebrated',()=>assert.equal(G.crossing(state([]),state([entry('a',59)]),today,C),null));
test('Further above goal is not re-celebrated',()=>assert.equal(G.crossing(state([entry('a',60)]),state([entry('a',60),entry('b',1)]),today,C),null));
test('Unknown protein values cannot yield exact goal crossing',()=>assert.equal(G.crossing(state([]),state([entry('a',80,today,1,2)]),today,C),null));
test('Past date entries never trigger today',()=>assert.equal(G.crossing(state([]),state([entry('a',80,other)]),today,C),null));
test('Changing target alone does not trigger',()=>{const a=state([entry('a',50)]),b=structuredClone(a);b.profile.manual.protein=40;assert.equal(G.crossing(a,b,today,C),null)});
test('No fake zero target on missing profile',()=>{const a=C.initial(),b=structuredClone(a);b.entries=[entry('a',90)];assert.equal(G.crossing(a,b,today,C),null)});
test('Inputs remain unchanged',()=>{const a=state([]),b=state([entry('a',70)]),s=JSON.stringify([a,b]);G.crossing(a,b,today,C);assert.equal(JSON.stringify([a,b]),s)});
console.log('TOTAL IMPORT/CELEBRATION CHECKS',count);
