'use strict';
const assert=require('node:assert/strict'),C=require('../core.js'),M=require('../macro-targets.js'),S=require('../sync-core.js'),Party=require('../protein-celebration.js');
const base={...C.initial().profile,age:40,sex:'m',weight:80,height:180,nutritionMode:'normal',activityPAL:1.4},keys=['energy','protein','fat','carbs','vitC'];
const calc=x=>M.calculate({...base,...x}),v=(r,k)=>r.values[k]?.value,near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
let passed=0;function test(name,fn){fn();passed++;console.log('PASS',name);}
test('legacy targets unchanged',()=>{const p={...base};delete p.nutritionMode;const r=C.targets(p);near(r.values.protein.value,64);assert.equal(r.values.carbs,undefined);});
test('normal weight-based protein',()=>near(v(calc({}),'protein'),64));
test('senior normal protein',()=>near(v(calc({age:65}),'protein'),80));
test('muscle 1.6 g/kg',()=>near(v(calc({nutritionMode:'muscle'}),'protein'),128));
test('sport 1.4 g/kg',()=>near(v(calc({nutritionMode:'sport'}),'protein'),112));
test('loss 1.2 g/kg',()=>near(v(calc({nutritionMode:'loss'}),'protein'),96));
test('energy matches DGE formula',()=>near(v(calc({}),'energy'),(.047*80-.01452*40+3.21+1.009)*239*1.4));
test('female formula',()=>near(v(calc({sex:'w'}),'energy'),(.047*80-.01452*40+3.21)*239*1.4));
test('normal fat 30%',()=>near(v(calc({}),'fat')*9,v(calc({}),'energy')*.3));
test('sport fat 25%',()=>{const r=calc({nutritionMode:'sport'});near(v(r,'fat')*9,v(r,'energy')*.25);});
test('macro energy balances all modes',()=>{for(const mode of Object.keys(M.presets)){const r=calc({nutritionMode:mode});near(v(r,'energy'),4*v(r,'protein')+4*v(r,'carbs')+9*v(r,'fat'));}});
test('muscle surplus is 5% small plan',()=>{const r=calc({nutritionMode:'muscle'});near(r.energyAdjustment,r.maintenance*.05);});
test('muscle surplus maximum 200',()=>near(calc({nutritionMode:'muscle',weight:160,height:230,activityPAL:2.2}).energyAdjustment,200));
test('loss deficit is 10%',()=>{const r=calc({nutritionMode:'loss'});near(r.energyAdjustment,-r.maintenance*.1);});
test('loss deficit maximum 300',()=>near(calc({nutritionMode:'loss',weight:160,height:230,activityPAL:2.2}).energyAdjustment,-300));
test('activity affects energy not protein',()=>{const a=calc({}),b=calc({activityPAL:2});assert.ok(v(b,'carbs')>v(a,'carbs'));assert.ok(v(b,'fat')>v(a,'fat'));near(v(b,'protein'),v(a,'protein'));near(v(b,'energy')/v(a,'energy'),2/1.4);});
test('reference weight assumption is explicit',()=>{const r=calc({weight:100});near(r.weight,22*1.8**2);assert.match(r.weightSource,/App-Annahme/);near(v(r,'protein'),r.weight*.8);});
test('own calculation weight has priority',()=>near(v(calc({weight:100,calcWeight:85}),'protein'),68));
test('weight update changes normal target',()=>near(v(calc({weight:75}),'protein'),60));
test('manual macros retained all modes',()=>{for(const mode of Object.keys(M.presets)){const manual={energy:2400,protein:133,fat:82,carbs:260},r=calc({nutritionMode:mode,manual});for(const k of keys.slice(0,4))near(v(r,k),manual[k]);}});
test('manual energy no additional deficit',()=>{const r=calc({nutritionMode:'loss',manual:{energy:2300}});near(v(r,'energy'),2300);near(r.energyAdjustment,0);});
test('own protein controls remaining carbohydrates',()=>{const a=calc({}),b=calc({manual:{protein:100}});near(v(a,'carbs')-v(b,'carbs'),36);});
test('conflicting own goals generate warning',()=>{const r=calc({manual:{energy:2400,protein:200,fat:150,carbs:400}});assert.ok(r.notes.some(n=>n.includes('passen nicht')));near(v(r,'carbs'),400);});
test('impossible remainder never negative',()=>{const r=calc({manual:{protein:900}});assert.equal(v(r,'carbs'),undefined);assert.ok(r.notes.some(n=>n.includes('gesamte Planenergie')));});
test('missing activity keeps protein only',()=>{const r=calc({activityPAL:null});near(v(r,'protein'),64);assert.equal(v(r,'energy'),undefined);});
test('manual energy with missing activity can derive macros',()=>assert.ok(calc({activityPAL:null,manual:{energy:2400}}).complete));
test('low energy guard even without activity',()=>{const r=calc({activityPAL:null,manual:{energy:1000}});near(v(r,'energy'),1000);assert.equal(v(r,'fat'),undefined);assert.equal(v(r,'carbs'),undefined);});
test('missing sex no invented energy',()=>assert.equal(v(calc({sex:''}),'energy'),undefined));
test('missing anthropometry suspends auto',()=>assert.deepEqual(calc({height:null}).values,{}));
test('special situation retains manual only',()=>assert.deepEqual(Object.keys(calc({special:true,manual:{protein:70}}).values),['protein']));
test('minor no automatic goals',()=>assert.deepEqual(calc({age:18}).values,{}));
test('noninteger age no automatic goals',()=>assert.deepEqual(calc({age:40.5}).values,{}));
test('low BMI no automatic goals',()=>assert.deepEqual(calc({weight:50}).values,{}));
test('very high BMI no automatic goals',()=>assert.deepEqual(calc({weight:150}).values,{}));
test('weight-loss safeguards',()=>{assert.deepEqual(calc({nutritionMode:'loss',age:65}).values,{});assert.deepEqual(calc({nutritionMode:'loss',weight:63}).values,{});});
test('invalid selectors rejected',()=>{for(const x of [{nutritionMode:'fake'},{nutritionMode:'toString'},{activityPAL:-1},{activityPAL:NaN},{activityPAL:Infinity},{activityPAL:'1.4'}])assert.throws(()=>M.validate({...base,...x}));});
test('legacy optional selector validation',()=>{M.validate(C.initial().profile);M.validate({...base,nutritionMode:'',activityPAL:null});});
test('profile fields survive validation/export/import',()=>{const s=C.initial();s.profile={...base};const b=C.validateState(JSON.parse(JSON.stringify(s)),keys);assert.equal(b.profile.nutritionMode,'normal');near(b.profile.activityPAL,1.4);});
test('micronutrient references and own vitamin goals unchanged',()=>{const p={...base,manual:{vitC:140}};const r=C.targets(p);near(r.values.vitC.value,140);near(r.values.calcium.value,1000);});
test('calculator never mutates profile',()=>{const p=structuredClone(base),before=JSON.stringify(p);M.calculate(p);assert.equal(JSON.stringify(p),before);});
test('mode fields support independent multi-device merge',()=>{const b=C.initial(),l=structuredClone(b),r=structuredClone(b);l.profile.nutritionMode='muscle';r.profile.activityPAL=1.8;const x=S.merge(b,l,r);assert.equal(x.conflicts.length,0);assert.equal(x.state.profile.nutritionMode,'muscle');near(x.state.profile.activityPAL,1.8);});
test('same-setting simultaneous edit becomes explicit conflict',()=>{const b=C.initial(),l=structuredClone(b),r=structuredClone(b);l.profile.nutritionMode='muscle';r.profile.nutritionMode='sport';assert.ok(S.merge(b,l,r).conflicts.length>0);});
test('celebration uses selected mode not old protein reference',()=>{const s=C.initial();s.profile={...base,nutritionMode:'muscle'};s.entries=[{date:'2026-09-26',n:{protein:{value:100,known:1,total:1,missing:[]}}}];assert.equal(Party.eligible(s,'2026-09-26',C),null);s.entries[0].n.protein.value=128;near(Party.eligible(s,'2026-09-26',C).target,128);});
console.log('TOTAL MACRO TESTS',passed);
