'use strict';
const assert=require('node:assert/strict'),C=require('../core.js'),M=require('../macro-goals.js'),S=require('../sync-core.js'),party=require('../protein-celebration.js');
const p={...C.initial().profile,age:40,weight:80,height:180,sex:'m',goal:'normal',pal:1.4};
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
let passed=0;const check=(name,fn)=>{fn();passed++;console.log('PASS',name);};
const t=(profile=p)=>C.targets(profile).values;
check('Four selectable presets',()=>assert.deepEqual(Object.keys(M.PRESETS),['normal','muscle','sport','loss']));
check('Legacy profile does not acquire goals without a choice',()=>{const q={...p};delete q.goal;assert.equal(t(q).energy,undefined);assert.equal(t(q).protein.value,64);});
check('DGE energy equation uses current weight and selected PAL',()=>near(t().energy.value,(.047*80-.01452*40+3.21+1.009)*239*1.4));
check('Female energy equation omits male increment',()=>near(t({...p,sex:'w'}).energy.value,(.047*80-.01452*40+3.21)*239*1.4));
check('Normal reference 0.8 grams/kg',()=>near(t().protein.value,64));
check('65-year age boundary uses 1 gram/kg',()=>near(t({...p,age:65}).protein.value,80));
check('Muscle planning preset is 1.6 g/kg',()=>near(t({...p,goal:'muscle'}).protein.value,128));
check('Sport planning preset is 1.4 g/kg',()=>near(t({...p,goal:'sport'}).protein.value,112));
check('Weight loss planning preset is 1.2 g/kg',()=>near(t({...p,goal:'loss'}).protein.value,96));
check('Muscle small surplus is explicit',()=>near(t({...p,goal:'muscle'}).energy.value,t().energy.value*1.05));
check('Sport does not double count exercise',()=>near(t({...p,goal:'sport'}).energy.value,t().energy.value));
check('Weight loss starts at 10 percent deficit',()=>near(t({...p,goal:'loss'}).energy.value,t().energy.value*.9));
check('Fat uses 30 percent energy and 9 kcal/g',()=>near(t().fat.value,t().energy.value*.3/9));
check('Carbohydrates use remaining energy',()=>near(t().carbs.value,(t().energy.value-64*4-t().fat.value*9)/4));
check('Four presets maintain 4/4/9 identity',()=>Object.keys(M.PRESETS).forEach(goal=>{const x=t({...p,goal});near(x.energy.value,4*x.protein.value+4*x.carbs.value+9*x.fat.value);}));
check('Weight changes recompute all automatic targets',()=>{const q={...p,weight:75};for(const k of ['energy','protein','fat','carbs'])assert.notEqual(t(q)[k].value,t()[k].value);});
check('No arbitrary default activity',()=>{const x=t({...p,pal:null});assert.equal(x.energy,undefined);assert.equal(x.fat,undefined);assert.equal(x.carbs,undefined);assert.equal(x.protein.value,64);});
check('Unknown sex does not guess energy needs',()=>{const x=t({...p,sex:''});assert.equal(x.energy,undefined);assert.equal(x.protein.value,64);});
check('Higher BMI requires confirmed protein calculation weight',()=>{const x=t({...p,weight:100});assert.equal(x.protein,undefined);assert.equal(x.carbs,undefined);assert.ok(x.energy);});
check('Reference suggestion is BMI22, never changes input',()=>{const before=JSON.stringify(p);near(M.referenceWeight(180),22*1.8**2);assert.equal(JSON.stringify(p),before);});
check('Explicit calculation weight used only for protein',()=>{const q={...p,weight:100,calcWeight:75},x=t(q);near(x.protein.value,60);near(x.energy.value,(.047*100-.01452*40+3.21+1.009)*239*1.4);});
check('Higher BMI muscle preset has no automatic surplus',()=>{const q={...p,weight:100,calcWeight:75,goal:'muscle'};near(t(q).energy.value,t({...q,goal:'normal'}).energy.value);});
check('Manual energy retained without applying another deficit',()=>{const x=t({...p,goal:'loss',manual:{energy:2000}});near(x.energy.value,2000);near(x.fat.value,2000*.3/9);});
check('Manual protein kept and reduces automatic carbs',()=>{const x=t({...p,manual:{protein:150}});assert.equal(x.protein.type,'Eigenes Ziel');near(x.protein.value,150);near(x.carbs.value,(x.energy.value-600-x.fat.value*9)/4);});
check('Manual fat changes remaining carbohydrates',()=>{const x=t({...p,manual:{fat:70}});near(x.fat.value,70);near(x.carbs.value,(x.energy.value-64*4-70*9)/4);});
check('Manual carbs are not overwritten',()=>near(t({...p,manual:{carbs:220}}).carbs.value,220));
check('Conflicting own macro sum gets a warning',()=>assert.ok(M.calculate({...p,manual:{energy:2000,protein:150,carbs:600,fat:100}}).notes.some(n=>n.includes('passen rechnerisch'))));
check('Never invent negative carbohydrate target',()=>assert.equal(t({...p,manual:{energy:1800,protein:400,fat:100}}).carbs,undefined));
check('All four personal goals are preserved when automation is suspended',()=>{const q={...p,special:true,manual:{energy:2000,protein:100,fat:60,carbs:265}};for(const k of Object.keys(q.manual))near(t(q)[k].value,q.manual[k]);});
check('Special situation disables all new automatic goals',()=>{const x=t({...p,special:true});for(const k of ['energy','protein','carbs','fat'])assert.equal(x[k],undefined);});
check('No ordinary adult macro plan for minors',()=>{const x=t({...p,age:16});for(const k of ['energy','protein','carbs','fat'])assert.equal(x[k],undefined);});
check('No automated diet when underweight',()=>{const x=t({...p,goal:'loss',weight:55});for(const k of ['energy','protein','carbs','fat'])assert.equal(x[k],undefined);});
check('No automatic reduction below BMI20',()=>assert.equal(t({...p,goal:'loss',weight:64}).energy,undefined));
check('No automatic reduction from age65',()=>assert.equal(t({...p,goal:'loss',age:65}).energy,undefined));
check('Conservative calorie floor does not generate low automatic plan',()=>assert.equal(t({...p,goal:'loss',age:55,sex:'w',height:152,weight:48}).energy,undefined));
check('No inferred additional macros from extreme own calorie goal',()=>{const x=t({...p,manual:{energy:900}});assert.equal(x.energy.value,900);assert.equal(x.fat,undefined);assert.equal(x.carbs,undefined);});
check('Micronutrients never scale by preset',()=>{const a=t(p),b=t({...p,goal:'muscle'});for(const k of Object.keys(a).filter(k=>!['energy','protein','carbs','fat'].includes(k)))assert.deepEqual(a[k],b[k]);});
check('No mutation of profile or manual targets',()=>{const a=JSON.stringify(p);M.calculate(p);C.targets(p);assert.equal(JSON.stringify(p),a);});
check('New fields survive full backup round trip',()=>{const a=C.initial();a.profile={...p};const b=C.validateState(JSON.parse(JSON.stringify(a)),['energy','protein','fat','carbs']);assert.equal(b.profile.goal,'normal');assert.equal(b.profile.pal,1.4);});
check('Unknown preset is rejected',()=>assert.throws(()=>M.validate({...p,goal:'__proto__'})));
check('Unknown activity is rejected',()=>assert.throws(()=>M.validate({...p,pal:1.7})));
check('Optional legacy goal and PAL valid',()=>M.validate(C.initial().profile));
check('Different household profiles use different plans',()=>{const a=t({...p,goal:'normal'}),b=t({...p,weight:65,goal:'muscle'});assert.notEqual(a.protein.value,b.protein.value);});
check('Celebration consumes new saved target, not old reference',()=>{const s=C.initial();s.profile={...p,goal:'muscle'};s.entries=[{date:'2026-09-26',n:{protein:{value:100,known:1,total:1,missing:[]}}}];assert.equal(party.eligible(s,'2026-09-26',C),null);s.entries[0].n.protein.value=128;assert.equal(party.eligible(s,'2026-09-26',C).target,128);});
check('Same goal field conflict is not silently resolved',()=>{const a=C.initial();a.profile={...p};const b=C.clone(a),c=C.clone(a);b.profile.goal='muscle';c.profile.goal='loss';assert.ok(S.merge(a,b,c).conflicts.length>0);});
check('Independent goal and PAL edits merge',()=>{const a=C.initial();a.profile={...p};const b=C.clone(a),c=C.clone(a);b.profile.goal='muscle';c.profile.pal=1.8;const m=S.merge(a,b,c);assert.equal(m.conflicts.length,0);assert.equal(m.state.profile.goal,'muscle');assert.equal(m.state.profile.pal,1.8);});
console.log('TOTAL MACRO GOAL TESTS',passed);
