'use strict';
const assert=require('node:assert/strict'),P=require('../portion-normalizer.js');
global.NK_PORTIONS=P;
const S=require('../scanner.js');
let count=0;function test(name,fn){fn();count++;console.log('PASS',name);}const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
test('30 g scales all declared nutrients by 100/30',()=>{const r=P.convert({energy:150,protein:3,fat:9,vitB12:.3,iron:.6}, {},30,'g');assert.equal(r.basis,'g');near(r.n.energy,500);near(r.n.protein,10);near(r.n.fat,30);near(r.n.vitB12,1);near(r.n.iron,2);});
test('250 ml downscales without converting mass',()=>{const r=P.convert({protein:10}, {},250,'ml');assert.equal(r.basis,'ml');near(r.n.protein,4);});
test('100 is identity',()=>near(P.convert({protein:3.5}, {},100,'g').n.protein,3.5));
test('comma decimals in amounts and nutrients',()=>near(P.convert({protein:'3,05'}, {},'30,5','g').n.protein,10));
test('zero is known, blanks are not zero',()=>{const n=P.convert({sugar:0,fiber:null,protein:'',fat:undefined}, {},30,'g').n;assert.equal(n.sugar,0);assert.equal(n.fiber,null);assert.equal(n.protein,null);assert.equal(n.fat,null);});
test('normalisation never mutates or compounds source',()=>{const n={protein:3};near(P.convert(n,{},30,'g').n.protein,10);near(P.convert(n,{},60,'g').n.protein,5);near(P.convert(n,{},30,'g').n.protein,10);assert.deepEqual(n,{protein:3});});
for(const value of ['','0','-30','NaN','Infinity','1e3','30g','1/2',100001])test('reject invalid source quantity '+value,()=>assert.throws(()=>P.convert({protein:3},{},value,'g')));
test('reject mass-to-volume or portion labels instead of units',()=>assert.throws(()=>P.convert({protein:3},{},30,'portion')));
test('reject negative or malformed raw values',()=>{for(const v of [-1,NaN,Infinity,'1..2','10%'])assert.throws(()=>P.convert({protein:v},{},30,'g'));});
test('less-than bound remains unknown but is normalised',()=>{const r=P.convert({sugar:null},{sugar:'< 0.5 g'},50,'g');assert.equal(r.n.sugar,null);assert.ok(r.q.sugar.startsWith('< 1 g pro 100 g'));});
test('corrected exact value replaces less-than note',()=>assert.deepEqual(P.convert({sugar:0},{sugar:'< 0.5 g'},30,'g').q,{}));
test('only header-like portions are suggested',()=>assert.deepEqual(P.hints('Pro Portion (30 g)\nEiweiss 3 g\nFett 9 g'),[{amount:30,unit:'g'}]));
test('no invented 100 g when header is missing',()=>assert.equal(P.hints('Eiweiss 3 g\nFett 9 g').length,0));
test('two header columns preserve their order',()=>assert.deepEqual(P.hints('pro 100 g | pro 30 g'),[{amount:100,unit:'g'},{amount:30,unit:'g'}]));
test('photo parser source 30 g then normalisation',()=>{const r=S.parse('Pro Portion (30 g)\nEnergie 150 kcal\nFett 9 g\nEiweiss 3 g\nVitamin B12 0,3 µg');const n=P.convert(r.n,r.q,30,'g').n;near(n.energy,500);near(n.protein,10);near(n.vitB12,1);});
test('right hand portion values, not percent RI',()=>{const t='pro 100 g | pro 30 g\nEnergie 500 kcal 150 kcal 8 %\nFett 30 g 9 g 13 %\nEiweiss 10 g 3 g 6 %';const r=S.parse(t,'last');near(P.convert(r.n,r.q,30,'g').n.protein,10);near(r.n.energy,150);});
test('ambiguous singleton row not silently used as portion',()=>{const r=S.parse('pro 100 g | pro 30 g\nFett 30 g 9 g\nEiweiss 10 g','last');assert.equal(r.n.protein,undefined);assert.ok(r.warnings.some(w=>w.includes('zuordnen')));});
test('declared negative value not silently made positive',()=>assert.equal(S.parse('Eiweiss -3 g').n.protein,undefined));
console.log('TOTAL',count);
