'use strict';const assert=require('node:assert/strict'),P=require('../product-import-core.js'),C=require('../core.js'),Party=require('../protein-celebration.js');let count=0;const test=(s,f)=>{f();console.log('PASS',s);count++;};
const url='https://www.coop.ch/de/lebensmittel/redefine-vegane-alternative-zu-flank-steak/p/7451865';
test('Tracking query and fragment removed',()=>assert.equal(P.coopURL(url+'?gclid=x#nutrition'),url));
test('Product query extracted without tracking',()=>assert.equal(P.queryFromURL(url),'redefine flank steak'));
for(const bad of ['http://www.coop.ch/de/food/p/7451865','https://coop.ch.evil.test/de/food/p/7451865','https://user:pass@www.coop.ch/de/food/p/7451865','https://127.0.0.1/de/food/p/7451865','https://www.coop.ch:444/de/food/p/7451865','https://www.coop.ch/de/search','https://www.coop.ch/de/food/%2e%2e/p/7451865'])test('Unsafe or unsupported URL rejected '+bad,()=>assert.throws(()=>P.coopURL(bad)));
const table='<h1>Testprodukt</h1><div>Durchschnittliche Nährwerte pro:</div><div>100g</div><li>Energie 790 kJ</li><li>Energie 188 kcal</li><li>Fett 6.6g</li><li>davon gesättigte Fettsäuren 0.8g</li><li>Kohlenhydrate 4g</li><li>davon Zucker 1.9g</li><li>Nahrungsfasern (Ballaststoffe) 4.5g</li><li>Eiweiss 26g</li><li>Salz 0.88g</li><li>Vitamin B12 2.5µg</li>';
test('Declared fields remain in their units',()=>{const f=P.parseCoop(table,url);assert.equal(f.n.protein,26);assert.equal(f.n.energy,188);assert.equal(f.n.vitB12,2.5);assert.equal(f.n.iron,undefined);assert.equal(f.basis,'g');});
test('No assumption on portion table',()=>assert.throws(()=>P.parseCoop(table.replace('100g','30g'),url)));
test('No arbitrary product text parsed as nutrition',()=>assert.throws(()=>P.parseCoop('<h1>Steak</h1><p>Viel Protein!</p>',url)));
test('Script does not execute',()=>{P.parseCoop(table+'<script>throw Error("bad")</script>',url);assert.equal(global.bad,undefined);});
test('Less than is not an exact zero',()=>{const f=P.parseCoop(table.replace('Zucker 1.9g','Zucker &lt; 0.5g'),url);assert.equal(f.n.sugar,null);assert.ok(f.q.sugar.includes('< 0.5g'));});
test('Energy without a unit is not invented',()=>{const f=P.parseCoop(table.replace('790 kJ','790').replace('188 kcal','188'),url);assert.equal(f.n.energy,undefined);});
const day=C.dateKey(),s=C.initial();s.profile.manual.protein=50;const entry=(id,val,known=1,total=1,date=day)=>({id,date,n:{protein:{value:val,known,total,missing:[]}}});
test('No celebration without entries',()=>assert.equal(Party.eligible(s,day,C),null));
test('No celebration before goal',()=>{s.entries=[entry('a',49)];assert.equal(Party.eligible(s,day,C),null);});
test('Celebrate exact target',()=>{s.entries=[entry('a',50)];assert.equal(Party.eligible(s,day,C).target,50);});
test('Celebrate higher recorded amount once without changing target',()=>{s.entries=[entry('a',62)];assert.equal(Party.eligible(s,day,C).target,50);});
test('No party for partial known intake',()=>{s.entries=[entry('a',62,1,2)];assert.equal(Party.eligible(s,day,C),null);});
test('No party for another date',()=>{s.entries=[entry('a',62,1,1,'2000-01-01')];assert.equal(Party.eligible(s,day,C),null);});
test('No party with no valid target',()=>{s.profile.manual={};s.entries=[entry('a',62)];assert.equal(Party.eligible(s,day,C),null);});
console.log('TOTAL',count);
