'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),C=require('../core.js'),P=require('../product-portions.js'),S=require('../food-search.js');
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../data.js'),'utf8'),ctx);const D=ctx.window.NK_DATA,keys=D.nutrients.map(n=>n.key);let passed=0;
function test(n,f){f();passed++;console.log('PASS',n);}const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} / ${b}`);
const f={id:'test-food',name:'Synthetic product',basis:'g',density:null,n:Object.fromEntries(keys.map(k=>[k,null])),portion:{label:'Stück',size:50,unit:'g'}};Object.assign(f.n,{energy:180,protein:12,carbs:9,fat:10,sugar:0});
test('two 50g pieces are 100g',()=>near(C.factor(f,2,'piece'),1));
test('half a piece is supported',()=>near(C.factor(f,'0,5','piece'),.25));
test('piece snapshot calories and protein',()=>{const n=C.snapshot(f,2,'piece',null,keys);near(n.energy.value,180);near(n.protein.value,12);assert.equal(n.sugar.value,0);assert.equal(n.vitB12.value,null);});
test('millilitre cup needs no density',()=>near(C.factor({...f,basis:'ml',portion:{label:'Becher',size:150,unit:'ml'}},2,'piece'),3));
test('grams and millilitres never silently mixed',()=>assert.throws(()=>C.factor({...f,portion:{...f.portion,unit:'ml'}},2,'piece')));
test('pieces without known size rejected',()=>assert.throws(()=>C.factor({...f,portion:null},2,'piece')));
test('bad piece sizes rejected',()=>[0,-1,Infinity,NaN,'50',100001].forEach(size=>assert.throws(()=>C.validateFood({...f,portion:{...f.portion,size}},keys))));
test('empty label rejected',()=>assert.throws(()=>C.validateFood({...f,portion:{...f.portion,label:''}},keys)));
test('fractional piece label and total visible',()=>assert.equal(P.describe(f,1.5,'piece'),'1.5 Stück (75 g)'));
test('standard grams unaffected',()=>near(C.factor(f,250,'g'),2.5));
const ingredient={food:f,quantity:2,unit:'piece',density:null},i=P.canonical(ingredient);
test('recipe stored in compatible units',()=>{near(i.quantity,100);assert.equal(i.unit,'g');assert.equal(i.portionUse.quantity,2);assert.equal(ingredient.unit,'piece');});
test('stored recipe reopens as pieces',()=>{const v=P.hydrate(i);assert.equal(v.unit,'piece');near(v.quantity,2);});
test('changed measure invalidates stale portion count',()=>assert.equal(P.hydrate({...i,quantity:200}).unit,'g'));
const recipe={id:'test-recipe',name:'Synthetic recipe',servings:2,finalWeight:100,ingredients:[i]};
test('recipe serving calculation remains exact',()=>near(C.recipePortion(recipe,1,'portion',keys).protein.value,6));
test('recipe mass calculation retains pieces',()=>near(C.recipeWeight(recipe),100));
test('historical piece amount remains independent',()=>{const entry=P.entryAmount(f,2,'piece');f.portion.size=60;assert.equal(entry.amountText,'2 Stück (100 g)');assert.equal(P.scaledEntry(entry,.5).amountText,'1 Stück (50 g)');f.portion.size=50;});
test('copy twice without cumulative label nesting',()=>{let e=P.entryAmount(f,2,'piece');e={...e,...P.scaledEntry(e,.5)};assert.equal(P.scaledEntry(e,2).amountText,'2 Stück (100 g)');});
test('backup validates piece metadata and recipe',()=>{const s=C.initial();s.foods=[f];s.recipes=[recipe];const n=C.validateState(JSON.parse(JSON.stringify(s)),keys);assert.equal(n.foods[0].portion.size,50);assert.equal(n.recipes[0].ingredients[0].portionUse.quantity,2);});
test('unknown nutrients still unknown',()=>assert.equal(C.recipeTotal(recipe,keys).vitB12.value,null));
test('Ei finds whole eggs before unrelated words',()=>assert.ok(['blv-1070','blv-290'].includes(S.select(D.foods,'Ei')[0].id)));
test('Eier cooked state is explicit',()=>assert.equal(S.select(D.foods,'Eier gekocht')[0].id,'blv-1070'));
test('Eier roh does not become cooked',()=>assert.equal(S.select(D.foods,'Ei roh')[0].id,'blv-290'));
test('own copy of an egg remains searchable',()=>assert.equal(S.select([{...D.foods.find(f=>f.id==='blv-290'),id:'own-egg'}],'Ei').length,1));
test('no false vegan egg match',()=>assert.equal(S.select(D.foods.filter(f=>['blv-1070','blv-290'].includes(f.id)),'vegan Ei').length,0));
test('plural lentils and chickpeas found',()=>{assert.ok(S.select(D.foods,'Linsen').length);assert.ok(S.select(D.foods,'Kichererbsen').length);});
test('brokkoli spelling supported',()=>assert.ok(S.select(D.foods,'Brokkoli').length));
test('data source remains unchanged',()=>assert.equal(D.foods.length,1246));
const scanner=require('../scanner.js');
test('Swiss nutritional text reads fibre',()=>assert.equal(scanner.parse('pro 100 g\nNahrungsfasern 6 g\nEiweiss 12 g').n.fiber,6));
console.log('TOTAL PIECE AND SEARCH TESTS',passed);
