'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const R=require('../release-notes-core.js'),D=require('../release-notes/catalog.js'),C=require('../core.js'),S=require('../sync-core.js');
let passed=0;function test(name,fn){fn();passed++;console.log('PASS',name);}
const copy=C.clone,b=C.initial();
test('v1.9 baseline normalized',()=>assert.equal(R.normalize('1.9'),'1.9.0'));
test('Semver numerically orders 1.10 after 1.9',()=>assert.equal(R.compare('1.10.0','1.9.9'),1));
test('Patch ordering is numeric',()=>assert.equal(R.compare('1.9.11','1.9.2'),1));
test('Major ordering is numeric',()=>assert.equal(R.compare('2.0.0','1.99.999'),1));
test('Equality normalizes',()=>assert.equal(R.compare('1.9','1.9.0'),0));
test('Invalid types and versions rejected',()=>{for(const v of [null,{},[],1,'v1.9.0','1.9.0-beta','01.9.0','1.9.-1','1.9.0<script>','9999999.1.1'])assert.equal(R.normalize(v),null);});
test('No marker exposes all releases starting at baseline',()=>assert.deepEqual(R.unread(D,null,'1.9.1').map(r=>r.version),['1.9.1','1.9.0']));
test('Confirmed current version not repeated',()=>assert.equal(R.unread(D,'1.9.1','1.9.1').length,0));
test('Baseline confirmation leaves patch only',()=>assert.deepEqual(R.unread(D,'1.9.0','1.9.1').map(r=>r.version),['1.9.1']));
test('Rollback cannot display future release',()=>assert.deepEqual(R.available(D,'1.9.0').map(r=>r.version),['1.9.0']));
test('Confirmed future stand retained during rollback',()=>assert.equal(R.unread(D,'1.10.0','1.9.1').length,0));
test('Invalid marker behaves as first load',()=>assert.equal(R.unread(D,'bad','1.9.1').length,2));
test('Skipped releases all included',()=>{const d=copy(D);for(const version of ['1.10.0','1.10.2','2.0.0'])d.releases.push({...copy(D.releases[0]),version});assert.deepEqual(R.unread(d,'1.9.0','1.10.2').map(r=>r.version),['1.10.2','1.10.0','1.9.1']);});
test('Out-of-order manifest sorted without mutation',()=>{const before=JSON.stringify(D);R.available(D,'1.9.1');assert.equal(JSON.stringify(D),before);});
test('Duplicate entries rejected',()=>{const d=copy(D);d.releases.push(d.releases[0]);assert.throws(()=>R.validate(d));});
test('No backfill before v1.9 allowed',()=>{const d=copy(D);d.releases.push({...copy(D.releases[0]),version:'1.8.9'});assert.throws(()=>R.validate(d));});
test('Incomplete changelog rejected',()=>assert.throws(()=>R.validate({schema:1,releases:[{version:'1.9.0'}]})));
test('Current app has release notes',()=>assert.ok(D.releases.some(r=>r.version===JSON.parse(fs.readFileSync(path.join(__dirname,'../version.json'))).version)));
test('Markdown available for each release',()=>D.releases.forEach(r=>assert.ok(fs.existsSync(path.join(__dirname,'../release-notes/v'+r.version+'.md')))));
test('Old profile without marker remains identical',()=>assert.deepEqual(C.validateState(copy(b),[]),b));
test('Malformed marker removed without blocking diary',()=>{const s=copy(b);s.profile.releaseNotesSeen={bad:true};assert.deepEqual(C.validateState(s,[]),b);});
test('Valid marker survives state validation',()=>{const s=copy(b);s.profile.releaseNotesSeen='1.9';assert.equal(C.validateState(s,[]).profile.releaseNotesSeen,'1.9.0');});
test('Only marker merged with remote body-data edit',()=>{const l=copy(b),r=copy(b);l.profile.releaseNotesSeen='1.9.1';r.profile.age=40;const m=S.merge(b,l,r);assert.equal(m.conflicts.length,0);assert.equal(m.state.profile.age,40);assert.equal(m.state.profile.releaseNotesSeen,'1.9.1');});
test('Concurrent acknowledgements prefer highest without conflict',()=>{const l=copy(b),r=copy(b);l.profile.releaseNotesSeen='1.9.1';r.profile.releaseNotesSeen='1.10.0';const m=S.merge(b,l,r);assert.equal(m.conflicts.length,0);assert.equal(m.state.profile.releaseNotesSeen,'1.10.0');});
test('Legacy metadata loss does not downgrade',()=>{const base=copy(b),l=copy(b),r=copy(b);base.profile.releaseNotesSeen='1.9.1';l.profile.releaseNotesSeen='1.9.0';assert.equal(S.merge(base,l,r).state.profile.releaseNotesSeen,'1.9.1');});
test('Legacy merge preserves read stand',()=>{const l=copy(b),r=copy(b);r.profile.releaseNotesSeen='1.9.1';assert.equal(S.merge(null,l,r).state.profile.releaseNotesSeen,'1.9.1');});
test('User-data conflicts remain explicit',()=>{const l=copy(b),r=copy(b);l.profile.weight=80;r.profile.weight=81;l.profile.releaseNotesSeen='1.9.1';r.profile.releaseNotesSeen='1.9.0';const m=S.merge(b,l,r);assert.deepEqual(m.conflicts,['profile.weight']);assert.equal(m.state.profile.releaseNotesSeen,'1.9.1');});
test('Releases never alter unrelated collections',()=>{const l=copy(b),r=copy(b);l.profile.releaseNotesSeen='1.9.1';r.foods=[{id:'remote',name:'Synthetic'}];const m=S.merge(b,l,r);assert.deepEqual(m.state.foods,r.foods);assert.deepEqual(m.state.entries,[]);assert.deepEqual(m.state.recipes,[]);});
test('Absent metadata does not get silently initialised',()=>assert.ok(!Object.hasOwn(S.merge(b,b,b).state.profile,'releaseNotesSeen')));
console.log('TOTAL RELEASE NOTE TESTS',passed);
