'use strict';
const assert=require('node:assert/strict'),C=require('../core.js'),R=require('../report-core.js'),SYNC=require('../sync-core.js');
let passed=0;const test=(name,fn)=>{fn();passed++;console.log('PASS',name);};
global.window=global;require('../data.js');const N=NK_DATA.nutrients,keys=N.map(n=>n.key);
const p={...C.initial().profile,age:40,sex:'m',height:180,weight:80,manual:{protein:100,vitC:100,calcium:1000,energy:2000,fat:60,carbs:250,sugar:5}};
function entry(id,date,values){return {id,date,name:'Test '+id,kind:'food',meal:0,n:Object.fromEntries(keys.map(k=>[k,{value:values[k]??null,known:values[k]!=null?1:0,total:1,missing:values[k]!=null?[]:['Test '+id]}]))};}
function state(){const s=C.initial();s.profile=C.clone(p);s.entries=[entry('a','2026-09-21',{protein:100,vitC:120,calcium:500,energy:2000,fat:60,carbs:250,sugar:3}),entry('b','2026-09-22',{protein:100,vitC:80,calcium:500,energy:2000,fat:60,carbs:250,sugar:3}),entry('c','2026-09-23',{protein:30,vitC:200,calcium:300})];s.days={'2026-09-21':{complete:true},'2026-09-22':{complete:true},'2026-09-23':{complete:false}};return s;}
const opts={frequency:'weekly',anchor:'2026-09-26',today:'2026-09-26'};const row=(s,k,o={})=>R.build(s,N,{...opts,...o}).rows.find(x=>x.key===k);
test('Default weekly without modifying legacy profile',()=>{const s=state();assert.equal(R.frequency(s.profile),'weekly');assert.equal(s.profile.reportFrequency,undefined);});
test('Daily weekly and monthly frequency accepted',()=>Object.keys(R.FREQUENCIES).forEach(f=>assert.equal(R.checkFrequency(f),f)));
test('Unsupported frequency rejected',()=>assert.throws(()=>R.checkFrequency('yearly')));
test('Calendar week starts Monday and ends Sunday',()=>assert.deepEqual(R.period('weekly','2026-09-26'),{frequency:'weekly',start:'2026-09-21',end:'2026-09-27',id:'weekly:2026-09-21'}));
test('Sunday belongs to preceding Monday',()=>assert.equal(R.period('weekly','2026-09-27').start,'2026-09-21'));
test('Week spans year boundary correctly',()=>assert.equal(R.period('weekly','2027-01-01').start,'2026-12-28'));
test('Leap February is 29 days',()=>assert.equal(R.period('monthly','2024-02-03').end,'2024-02-29'));
test('Non leap February is 28 days',()=>assert.equal(R.period('monthly','2026-02-03').end,'2026-02-28'));
test('Daily exact day',()=>assert.equal(R.period('daily','2026-09-26').start,R.period('daily','2026-09-26').end));
test('Invalid calendar day rejected',()=>assert.throws(()=>R.period('daily','2026-02-30')));
test('Previous monthly report crosses January',()=>assert.equal(R.previous('monthly','2026-01-03').start,'2025-12-01'));
test('Report dates unaffected by daylight saving',()=>assert.equal(R.period('weekly','2026-03-29').end,'2026-03-29'));
test('Unlogged days excluded not zero-filled',()=>{const r=R.build(state(),N,opts);assert.equal(r.selectedDays,3);assert.equal(r.unrecordedDays,3);assert.equal(r.futureDays,1);assert.equal(r.recordedDays,3);});
test('Mean uses recorded days denominator',()=>assert.equal(row(state(),'vitC').average,400/3));
test('Incomplete diary yields provisional not success',()=>assert.equal(row(state(),'vitC').status,'provisional'));
test('Complete-only mean correctly excludes open day',()=>{const r=row(state(),'vitC',{completeOnly:true});assert.equal(r.average,100);assert.equal(r.status,'met');assert.equal(r.selectedDays,2);});
test('Goal under target only for known completed entries',()=>assert.equal(row(state(),'calcium',{completeOnly:true}).status,'below'));
test('Unknown vitamin not zero or failure',()=>{const r=row(state(),'vitB12',{completeOnly:true});assert.equal(r.average,null);assert.equal(r.status,'gaps');});
test('One unknown day keeps lower-bound mean and gaps',()=>{const s=state();s.entries[1].n.vitC={value:null,known:0,total:1,missing:['B']};const r=row(s,'vitC',{completeOnly:true});assert.equal(r.average,60);assert.equal(r.hasGaps,true);assert.equal(r.status,'gaps');});
test('Partially known recipe not full',()=>{const s=state();s.entries[0].n.vitC={value:120,known:1,total:2,missing:['Zutat']};assert.equal(row(s,'vitC',{completeOnly:true}).status,'gaps');});
test('Known zero preserved',()=>{const s=state();s.entries.forEach(e=>e.n.vitC.value=0);const r=row(s,'vitC',{completeOnly:true});assert.equal(r.average,0);assert.equal(r.status,'below');});
test('Empty period no false failures',()=>{const r=R.build(C.initial(),N,opts);assert.equal(r.selectedDays,0);assert.equal(r.counts.met,0);assert.ok(r.rows.every(x=>x.average===null&&x.status==='no_data'));});
test('Empty completed flag not invented as zero intake',()=>{const s=C.initial();s.days['2026-09-21']={complete:true};assert.equal(R.build(s,N,opts).selectedDays,0);});
test('Future dated entries excluded',()=>{const s=state();s.entries.push(entry('future','2026-09-27',{vitC:10000}));assert.equal(R.build(s,N,opts).recordedDays,3);});
test('Folate incompatible no percent',()=>{const r=row(state(),'folate');assert.equal(r.status,'incompatible');assert.equal(r.percent,null);});
test('Missing vitamin K target explicit',()=>assert.equal(row(state(),'vitK').status,'no_target'));
test('Manual targets respected',()=>{const s=state();s.profile.manual.vitC=200;assert.equal(row(s,'vitC',{completeOnly:true}).status,'below');});
test('Manual report frequency survives validated backup roundtrip',()=>{const s=state();s.profile.reportFrequency='monthly';assert.equal(C.validateState(C.clone(s),keys).profile.reportFrequency,'monthly');});
test('Malformed imported report frequency rejected',()=>{const s=state();s.profile.reportFrequency={bad:1};assert.throws(()=>C.validateState(s,keys));});
test('Independent profile settings merge across devices',()=>{const s=state(),a=C.clone(s),b=C.clone(s);a.profile.reportFrequency='monthly';b.profile.weight=81;const r=SYNC.merge(s,a,b);assert.equal(r.conflicts.length,0);assert.equal(r.state.profile.reportFrequency,'monthly');assert.equal(r.state.profile.weight,81);});
test('Conflicting report frequencies need existing conflict workflow',()=>{const s=state(),a=C.clone(s),b=C.clone(s);a.profile.reportFrequency='daily';b.profile.reportFrequency='monthly';assert.ok(SYNC.merge(s,a,b).conflicts.includes('profile.reportFrequency'));});
test('Calories above goal not rewarded',()=>{const s=state();s.entries.slice(0,2).forEach(e=>e.n.energy.value=2600);assert.equal(row(s,'energy',{completeOnly:true}).status,'over_plan');});
test('Calories within declared plan tolerance',()=>assert.equal(row(state(),'energy',{completeOnly:true}).status,'within'));
test('Plan lower bound inclusive and below threshold',()=>{const s=state();s.entries.slice(0,2).forEach(e=>e.n.energy.value=1800);assert.equal(row(s,'energy',{completeOnly:true}).status,'within');s.entries.slice(0,2).forEach(e=>e.n.energy.value=1799);assert.equal(row(s,'energy',{completeOnly:true}).status,'under_plan');});
test('Sugar manual goal no assumed minimum',()=>assert.equal(row(state(),'sugar',{completeOnly:true}).status,'comparison'));
test('High vitamins not diagnosed toxic or better',()=>{const s=state();s.entries[0].n.vitC.value=3000;assert.equal(row(s,'vitC',{completeOnly:true}).status,'met');});
test('Trace elements grouped separately',()=>['iron','zinc','iodine','selenium'].forEach(k=>assert.equal(row(state(),k).group,'trace')));
test('Calendar archive deduplicates periods and ignores future',()=>{const s=state();s.entries.push(entry('future','2027-01-01',{}));assert.equal(R.history(s,'weekly','2026-09-26').length,2);});
test('Reports read snapshots without modifying history or goals',()=>{const s=state(),before=JSON.stringify(s);R.build(s,N,opts);assert.equal(JSON.stringify(s),before);});
test('CSV exposes partial qualifier and current reference basis',()=>{const text=R.csv(R.build(state(),N,opts),'Dimitri');assert.ok(text.includes('bekannte Teilmenge'));assert.ok(text.includes('Aktuelle gespeicherte Profilziele'));assert.ok(text.includes('Dimitri'));});
test('CSV neutralizes formula injection',()=>{const text=R.csv(R.build(state(),N,opts),'=IMPORTXML("url")');assert.ok(text.includes("'=IMPORTXML"));});
test('Equivalent raw current goals no retrospective mutation',()=>{const s=state(),before=JSON.stringify(s.entries);s.profile.manual.protein=120;assert.equal(row(s,'protein',{completeOnly:true}).target,120);assert.equal(JSON.stringify(s.entries),before);});
test('All selected days incomplete => no complete-only results',()=>{const s=state();s.days={};assert.equal(R.build(s,N,{...opts,completeOnly:true}).selectedDays,0);});
console.log('TOTAL REPORT TESTS',passed);
